### ISSUE TITLE
Passing "function" to jshint freezes browser

### ISSUE THREAD

**Issue by ladyd252** [jshint/jshint#2401] opened 2015-05-18 21:12 UTC
This can be reproduced by loading jshint into a browser tab with jquery (personally tested in chrome and safari):

    $('body').append('<script src="https://cdnjs.cloudflare.com/ajax/libs/jshint/2.7.0/jshint.js">')

and then passing in "function": JSHINT("function")

Appears to me from initial debugging that this is caused by functionparams() infinitely calling on checkPunctuators()

Seems like it never stops looking for a punctuator even though there is no more input.

Interestingly, typing in function in the live editor on jshint.com works fine- is there anything I'm missing or doing wrong?

Thanks!

**Comment by jugglinmike** [comment] 2015-05-18 21:24
Thanks for the report! Bad news: this is a duplicate of gh-2362 ("JSHINT('function') causes infinite loop in 2.7.0") and gh-2385 ("Infinite validation process (100% processor loading)"). Good news: gh-2338 has landed, so this should be resolved in the next release of JSHint (version > 2.7.0).

**Closed by jugglinmike** 2015-05-18 21:24 UTC

**Comment by ladyd252** [comment] 2015-05-18 21:35
Ah, sorry, couldn't find the other issues! Great to hear it's going to be
resolved, any idea when to expect the next release?

**Comment by jugglinmike** [comment] 2015-05-18 21:46
Good question. @rwaldron @caitp is there anything you'd like to get done before publishing a new release?

**Comment by caitp** [comment] 2015-05-18 21:47
Maybe It's worth fixing lodash for the docs site first

**Comment by jugglinmike** [comment] 2015-05-18 21:54
That's done--see gh-2329

**Comment by caitp** [comment] 2015-05-18 21:55
then by all means

**Comment by jugglinmike** [comment] 2015-05-18 22:13
Come to think of it, there are two changes we need to make to avoid breaking `enforceall`. I'll follow up with a pull request tomorrow morning.

**Comment by jugglinmike** [comment] 2015-05-19 14:47
See gh-2404
