### ISSUE TITLE
export as with const or let declared values throws 'not defined'

### ISSUE THREAD

**Issue by lrsjng** [jshint/jshint#2681] opened 2015-09-14 20:37 UTC
as this works great with `var` declarations it gives me a `a is not defined` in case of `let` or `const` declarations with jshint v2.8.0:

```js
// jshint esnext: true

const a = 1;
export {a as b};
//      ^ a is not defined
```

**Comment by lukeapage** [comment] 2015-09-15 11:38
Confirmed fixed in master and will be released as 2.9.1 (2.9.0 was reverted due to a number of regressions)

@jugglinmike what is the website running? 2.9.0 ? this bug doesn't happen there.

**Closed** 2015-09-15 11:38 UTC

**Comment by jugglinmike** [comment] 2015-09-15 13:28
Although this wasn't always the case, [the active version is now published on the index page itself](https://github.com/jshint/jshint.github.io/commit/3e383005fb141c313a520a5ed58de100155a40de). Currently, it's 2.8.0

**Comment by lrsjng** [comment] 2015-09-15 13:41
@lukeapage @jugglinmike seems to be the `undef` flag that causes the problem (checked on the index page too):

```js
// jshint esnext: true
// jshint undef: true

const a = 1;
export {a as b};
//      ^ a is not defined
```

**Comment by lrsjng** [comment] 2015-09-15 13:52
@lukeapage @jugglinmike all declaration variants:

```js
// jshint esnext: true
// jshint undef: true

const a = 1;
export {a as x};
//      ^ a is not defined

let b = 2;
export {b as y};
//      ^ b is not defined

var c = 3;
export {c as z};
//      ^ c is okay
```
