### ISSUE TITLE
remove install warning that jshint prefers to be installed globally

### ISSUE THREAD

**Issue by Pomax** [jshint/jshint#2805] opened 2015-12-15 17:14 UTC
NPM runs package script calls (`npm test`, `npm run yourownsscript`, `npm postinstall`, etc) with the execution environment appended with the `./node_modules` dir, so that CLI packages *don't* need to be installed globally to work propery.

Currently there is an installation warning `npm WARN prefer global jshint@2.8.0 should be installed with -g`, but this has not been necessary for a few NPM major versions now, so it's worth removing that warning to keep the install log clean.

**Comment by jugglinmike** [comment] 2016-01-03 15:41
Thanks for the report! This issue is a duplicate of gh-2642, which was closed because the behavior was corrected upstream in npm. You may be experiencing the problem due to a recent regression in that project: https://github.com/npm/npm/issues/8517. I'm going to close this because the fix is npm's responsibility and not JSHint's (and because the symptom is pretty benign).

**Closed by jugglinmike** 2016-01-03 15:41 UTC

**Comment by Pomax** [comment] 2016-01-03 17:04
Thanks, commented on the npm issue, hopefully that can get fixed soon =)
