### ISSUE TITLE
W100 is signaled in Node.js sources

### ISSUE THREAD

**Issue by acarstoiu** [jshint/jshint#2741] opened 2015-10-31 19:01 UTC
This warning
`"This character may get silently deleted by one or more browsers."`
is reported by JSHint even if there is a `"node": true` in the configuration file. Can be obtained with odd Unicode characters (written directly, UTF-8) on the current _**master**_ version (post _2.9.0_).

**Comment by jugglinmike** [comment] 2015-11-04 22:04
Thanks for the report! I'm unable to find the regression point based on your description. Could you share a small example that demonstrates the warning and the version of JSHint that does *not* warn for that input?

**Comment by acarstoiu** [comment] 2015-11-20 21:35
Sorry, I do not read regularly my emails, if you can believe that.
The fact that this issue is a regression was my assumption given [another Node.js-related problem](https://github.com/jshint/jshint/issues/2657) discovered shortly after the launch of 2.9.0. To avoid a misunderstanding, I removed this detail.

But the problem is *perfectly reproduceable* :bug:
Just use this `.jshintrc`
```js
{
	"node": true,
	"latedef": "nofunc",
	"laxbreak": true,
	"sub": true,
	"funcscope": true
}
```
on [a file as this](http://pastebin.com/V93fFb6s) (remove the JSHint comment to see the bug, of course).

**Comment by jugglinmike** [comment] 2016-04-23 16:11
I've started on a fix for this, but in all honesty, I don't understand W100 to begin with. [Warning W100 reads "This character may get silently deleted by one or more browsers."](https://github.com/jshint/jshint/blob/29dd071d66ee16d250ce63c0c4e061b74f7423ac/src/messages.js#L184) It's emitted when a character satisfies [the follow regular expression](https://github.com/jshint/jshint/blob/b554ffe61eabf6e3e3a2876a3a377271da308811/src/reg.js#L13-L15):

      /[\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/

One fix that I am considering is to limit emitting this warning to when JSHint's `browser` setting has been enabled. [This behavior has existed from the very first commit of JSLint](https://github.com/jshint/jshint/blob/ca120a731db548c0014320fa0c196edc613536ae/fulljslint.js#L895), and like many warnings from that era, the motivation is not clear to me. I don't actually know which browsers would exhibit this behavior, and I can't find justification online. So another fix would be to just remove the warning entirely. 

@mathiasbynens This is related to file encodings and web browsers, so naturally, I thought of you. Could you spare a moment to explain this to me?

**Comment by jugglinmike** [comment] 2017-09-27 13:33
@littledan I was just talking with @mathiasbynens about this. Do you have any input?

**Comment by mathiasbynens** [comment] 2017-09-27 19:00
That list of characters seems arbitrary to me. Since it’s not clear what browser behavior was referred to, I’d be okay with dropping this rule.

**Comment by jugglinmike** [comment] 2017-09-28 00:50
In that case, I will plan to remove the warning in the next release of JSHint. Thanks, Mathias!

**Comment by littledan** [comment] 2017-10-12 10:08
I'm not sure what behavior this is getting at either.

**Closed** 2018-07-10 18:41 UTC
Labels: P4, good first bug, help wanted
