### ISSUE TITLE
"asi" option is broken

### ISSUE THREAD

**Issue by Sven65** [jshint/jshint#3235] opened 2018-01-10 10:56 UTC
JSHint version: 2.9.5
Sourcecode: My entire codebase with mixed semicolons

Example file:

```js
class Analytics{
	constructor(cache, keyPrefix=""){
		this._cache = cache
	}

	_prepareKey(key, expires){
		return new Promise(async (resolve, reject) => {
			let exists = await this._cache.exists(key).catch(e => reject(e))

			if(!exists){
				await this._cache.set(key, 0).catch(e => reject(e))

				if(expires !== null){
					await this._cache.expire(key, expires).catch(e => reject(e))
				}
			}

			resolve()
		})
		
	}
}
```

Config:

```json
{
	"undef": true,
	"unused": true,
	"eqeqeq": true,
	"esversion": 6,
	"asi": true,
	"browser": false,
	"devel": true,
	"node": true,
	"loopfunc": true,
	"expr": true,
	"globals": {
		"ReDB": true
	}
}
```

Expected behaviour: All instances of missing semicolons should be ignored

Actual behavior: 90% of the errors are due to missing semicolons

Other: It seems to be within async/await functionality

**Comment by jugglinmike** [comment] 2018-01-15 03:31
Hi there @Sven65! Initially, I was at a loss on this one, but with the
information you added in your recent edit, the problem is much clearer. JSHint
does not currently support async functions, so the errors you are experiencing
are expected.

We're working hard to support async functions, though--you can check the status
of that work here:

https://github.com/jshint/jshint/issues/2604

In the mean time, I'm going to close this report since it's describing the same
feature request.

Thanks for taking the time to report!

**Closed by jugglinmike** 2018-01-15 03:31 UTC
