### ISSUE TITLE
Regular expression literal inside template literal not parsed

### ISSUE THREAD

**Issue by pornel** [jshint/jshint#2885] opened 2016-03-04 12:28 UTC
Regular expression literal, such as `/test/` is a valid expression, and template literals allow any expression, so this should work:

```js
`${/test/}`
```

However, this doesn't parse in jshint:

> Expected an identifier and instead saw '/'.
> Expected an identifier and instead saw '{a}'.

**Comment by jugglinmike** [comment] 2016-03-04 14:43
This is a duplicate of gh-2791 and has been resolved in `master` via gh-2792. The fix will be available in the next (post-2.9.1) version of JSHint.

**Closed by jugglinmike** 2016-03-04 14:43 UTC
