### ISSUE TITLE
latedef:true erroneously flags named exports as used before define

### ISSUE THREAD

**Issue by mikesherov** [jshint/jshint#2658] opened 2015-09-03 16:22 UTC
Version: 2.9.0, regressed from ~2.8.0

```
/*jshint latedef: true, esnext: true*/
export function hi() {
 return 1;
}
```

results in:

```
2	'hi' was used before it was defined.
```

**Comment by craigatk** [comment] 2015-09-03 16:48
I'm also seeing latedef enforced in 2.9.0 when I'm using a function before it's defined and I have ```"latedef": true``` in my ```.jshintrc``` file.

**Comment by exavatar** [comment] 2015-09-03 17:05
I am seeing jshint flag variables as they are being defined:

```
    837 |    var _instance;
                 ^ '_instance' was used before it was defined.
```

**Comment by lukeapage** [comment] 2015-09-04 15:56
@exavatar and @craigatk please can you post seperate issues with code samples? the export function is fixed in a pr, but your comments suggest different issues. 
They may be regressions or they may be code that should have given a warning previously but didn't (e. g.  jshint fixed a bug with a warning). No one else has reported those problems and we have tests covering what you describe so we need more info.  Thanks.

**Comment by craigatk** [comment] 2015-09-04 17:10
@lukeapage you're right, my case was likely caused by a code that should have given a warning before but didn't. Sorry for the confusion!

**Closed** 2015-09-08 22:46 UTC
Labels: ES6, Has PR, Regression
