### ISSUE TITLE
jshint does not allow es6 destructuring defaults

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2454] opened 2015-06-08 13:32 UTC
example from mdn..
```
function drawES6Chart({size = 'big', cords = { x: 0, y: 0 }, radius = 25} = {}) 
{
  console.log(size, cords, radius);
  // do some chart drawing
}
```

this produces lots of errors.

**Comment by lukeapage** [comment] 2015-06-08 13:32
the following too

```
var [missing = true] = [];
```

**Comment by jugglinmike** [comment] 2015-06-08 14:34
This is a duplicate of gh-1941, but a fix is on it's way! See gh-2391

**Closed by jugglinmike** 2015-06-08 14:34 UTC

**Comment by lukeapage** [comment] 2015-06-08 15:01
ah sorry, no idea why I didn't find that issue when I searched
