### ISSUE TITLE
Do not recognize ES6 regular expression flag

### ISSUE THREAD

**Issue by beizhedenglong** [jshint/jshint#2986] opened 2016-07-23 06:22 UTC
![image](https://cloud.githubusercontent.com/assets/12963675/17076258/d10218f0-50e0-11e6-9ba1-af6627b6626b.png)

**Comment by sstern6** [comment] 2016-08-02 23:26
@beizhedenglong thank you for finding this.  I was able to reproduce locally and dont mind making a PR for this unless you want to take a swing at it.  I think the issue is found with the internal logic of `function parseFinalSemicolon()` in src/jshint.js, specifically with `blockEnd` && `sameLine` but would like a core member to comment on this before proceeding with a PR.

**Comment by jugglinmike** [comment] 2016-08-03 13:57
@sstern6 the updated version of your comment is closer to the mark. This is a
bug I'd all but forgotten about until you commented here. I've submitted a fix
at gh-2999.

**Comment by jugglinmike** [comment] 2016-08-18 16:17
Resolved via gh-2999.

**Closed by jugglinmike** 2016-08-18 16:17 UTC
Labels: ES6, Has PR
