### ISSUE TITLE
Keyword alert reported as an unused variable

### ISSUE THREAD

**Issue by cmacleod42** [jshint/jshint#2374] opened 2015-05-11 09:25 UTC
eg
alert('Please choose a name for your saved game.');

reports alert in the unused variable list.

**Comment by nicolo-ribaudo** [comment] 2015-05-12 20:32
Can you post some more code?

**Comment by lukeapage** [comment] 2015-05-13 12:15
I *cannot* reproduce with
```
/* jshint unused: true, devel: true */
(function () {
alert('Please choose a name for your saved game.');
})();
```

**Comment by cmacleod42** [comment] 2015-05-14 12:10
I was using the online system, and the option "Development" is not on by 
default.

The code I was modifying here was not development code it is using 
alert() as a popup message for the person using the webpage.

So, no issue as such if you treat alert() as being for development.

**Comment by nicolo-ribaudo** [comment] 2015-05-14 13:01
@cmacleod42 Next time you report an issue, can you write some code to reproduce it?

@lukeapage I guess @cmacleod42 is doing something like this:
```javascript
/*jshint undef: true, devel: false, latedef: false */
alert();
function alert() {}
```
Warns: `'alert' is defined but never used.`

If you rename that function, all works well:
```javascript
/*jshint undef: true, devel: false, latedef: false */
warn();
function warn() {}
```

**Comment by cmacleod42** [comment] 2015-05-14 13:26
I did post code in my report of the issue it was reproduced in one of 
the replies I got
> |/* jshint unused: true, devel: true */
> (function () {
> alert('Please choose a name for your saved game.');
> })();|
This is a variation but the alert statement is identical

My code was just using an alert statement without ant function 
declaration but withing an other function
eg

> function PromptAndSave(no, exist)
> {
>     var n = '';
>     if (exist == 1)    n = GetSaveName(GetSaveGame("LSD"+no));
>
>     var na = prompt('Name of the saved game?', n);
>
>     if (na != null && na !== "")    {
>             if (na.length < 36)    {
>                 Save(no, na);
>             }    else {
>                 alert('The name of your saved game must not exceed 35 
> characters.  Please choose a different name.');
>             }
>     } else {
>         alert('Please choose a name for your saved game.');
>     }
> }

No where in my code do I define
function alert() etc

The issue was purely that I was using the online version of JSLint and 
the "Development" option was not enabled and it seems to warn on using 
alert()

**Comment by lukeapage** [comment] 2015-06-01 07:48
> The issue was purely that I was using the online version of JSLint and the "Development" option was not enabled and it seems to warn on using alert()

So this isn't a bug?

I can't reproduce any problems, using the online version of jshint and any of the code samples posted in this issue report.

with a slight modification of @nicolo-ribaudo code..

```
/*jshint undef: true, devel: true, latedef: false */
alert();
function alert() {}
```

I get a warning. Thats fixed on my soon to come up PR.

**Closed** 2015-06-23 22:10 UTC
