### ISSUE TITLE
camelcase:false had stopped to work

### ISSUE THREAD

**Issue by PavelPolyakov** [jshint/jshint#2448] opened 2015-06-05 22:38 UTC
Updated the grunt-contrib-jshint version , which led to the jshint update to the version 2.8.0 .

After that point, several ```camelcase:false``` comments had stopped to work.

In particular, I have the issue with this piece of code:

```javascript
prettifyData: function() {
                            /* jshint camelcase:false */
                            for(var key in this.data) {
                                if(Object(this.data).hasOwnProperty(key)) {
                                    this.data[key].prettyInterestRate = (this.data[key].interest_rate * 100).toFixed(1);
                                    this.data[key].prettyAmount = (this.data[key].amount / 100);
                                }
                            }
                            /* jshint camelcase:true */
                        }
```

jshint outputs the error
![image](https://cloud.githubusercontent.com/assets/839290/8016495/5a875588-0be4-11e5-8616-80b20a816bc0.png)

no matter what I do

For some reason, only the front-end javascript files were affected. All the node.js files are still ok with the ```camelcase``` comment-configurations.

Any thoughts?

Regards,

**Comment by nicolo-ribaudo** [comment] 2015-06-05 22:46
Can't reproduce on jshint.com

**Comment by jugglinmike** [comment] 2015-06-05 22:46
I can't reproduce this issue. The fact that it only effects some of your source files suggests there is something unique about your environment.

**Comment by PavelPolyakov** [comment] 2015-06-05 22:50
Here is the full file:
```javascript
(function () {
	angular.module('kreditech')
		.factory('CustomerRating', ['BaseModel', '$q', '$http', '$rootScope', 'utils',
			function CustomerRatingFactory(BaseModel, $q, $http, $rootScope, utils) {

				var CustomerRating =  BaseModel.extend(
					/*Prototype*/
					{
						constructor           : function CustomerRating() {

						},
                        loadInfo  : function() {
                            var defer = $q.defer();
                            var self = this;

                            $http
                                .get('/customer-rating')
                                .success(function (data) {
                                    self.data = data;

                                    self.prettifyData();

                                    defer.resolve(self.data);
                                })
                                .error(function (data) {
                                    defer.reject(data);
                                });

                            return defer.promise;
                        },
                        prettifyData: function() {
                            /* jshint camelcase:false */
                            for(var key in this.data) {
                                if(Object(this.data).hasOwnProperty(key)) {
                                    this.data[key].prettyInterestRate = (this.data[key].interest_rate * 100).toFixed(1);
                                    this.data[key].prettyAmount = (this.data[key].amount / 100);
                                }
                            }
                            /* jshint camelcase:true */
                        }
					},
					/*Static*/
					{
						/**
						 * @type CustomerRating
						 */
						instance     : null,
						/**
						 * As we need only one of this but we want to keep unify method to play with models
						 * in case we will require to use in another way. Implement singleton
						 * @returns {CustomerRating}
						 */
						getInstance : function () {
							if (!CustomerRating.instance) {
                                CustomerRating.instance = new CustomerRating();
							}

							return CustomerRating.instance;
						}
					}
				);

				return CustomerRating;
			}]
	);

})();
```

Our configuration:
```
options: {
                camelcase: true,
                curly    : true,
                forin    : true,
                freeze   : true,
                immed    : true,
                latedef  : true,
                newcap   : false,
                noarg    : true,
                noempty  : true,
                nonbsp   : true,
                nonew    : true,
                quotmark : 'single',
                undef    : true,
                //unused: true,
                //strict: true,
                esnext   : true,
                futurehostile : true,
                maxparams: 9,
                maxdepth : 3,
                globals  : {
                    'Promise': true,
                    '_'      : true,
                    'moment' : true,
                    window   : true,
                    validator: true,
                    gc       : true
                },
                predef   : ['angular','-Promise']
                //maxstatements: 10,
                //maxlen: 80
            }
```

**Comment by PavelPolyakov** [comment] 2015-06-05 23:28
It works if I put the comment-configuration here:
**WORKS**
```javascript
'use strict';
/* jshint camelcase:false */
(function () {
	angular.module('kreditech')
		.factory('CustomerRating', ['BaseModel', '$q', '$http',
			function CustomerRatingFactory(BaseModel, $q, $http) {
				var CustomerRating =  BaseModel.extend(
```

But it stops to work as soon as I put the comment-configuration inside the function:
**DOESNT WORK**
```javascript
'use strict';
/* jshint camelcase:false */
(function () {
	angular.module('kreditech')
		.factory('CustomerRating', ['BaseModel', '$q', '$http',
			function CustomerRatingFactory(BaseModel, $q, $http) {
/* jshint camelcase:false */
				var CustomerRating =  BaseModel.extend(
```

Before, I was able to select the piece of code where I can suppress the camelcase errors.

Am I able to do this right now?

**Comment by jugglinmike** [comment] 2015-06-05 23:36
Thanks for sharing the complete source code--that makes this much easier to diagnose. The bad news: this is a duplicate of gh-2411, so I'm going to close it. The good news: I've implemented a fix in gh-2427, so you can expect the next release of JSHint (>2.8.0) to function correctly!

In the mean time, you will either have to disable the warning for the whole file or move the function definition outside of the array literal--something like:

```js
(function () {
    function CustomerRatingFactory(BaseModel, $q, $http) {
        // your source code as normal ("ignore" will work here)
    }
    angular.module('kreditech')
        .factory('CustomerRating', ['BaseModel', '$q', '$http', CustomerRatingFactory]);
```

I know neither of those approaches are ideal, though. We'll do our best to get the fix published soon!

**Closed by jugglinmike** 2015-06-05 23:36 UTC

**Comment by PavelPolyakov** [comment] 2015-06-05 23:39
@jugglinmike 

Thanks!
