### ISSUE TITLE
Switch with multi-case near default are flagged for missing break

### ISSUE THREAD

**Issue by TWiStErRob** [jshint/jshint#3182] opened 2017-09-04 21:21 UTC
Consider this code:
```js
switch (...) {
  case 1:
  case 2:
  case 3:
    return "special";
  case 4:
  case 5:
    return "ok";
  case 6:
  default:
    return "whatever";
}
```
JSHint flags `case 6` with `Expected a 'break' statement before 'default'.`. I think this could be a bit more relaxed. If grouping 1-3 and 4-5 together is ok, than grouping 6-anything else should be ok too.

In general `default` obviously includes `6`, but rather than putting a comment or `jshint ignore`, or `case 6: /* falls through */\ndefault:`, it should be acceptable to call out that "*I know 6 is a valid case, and I choose to handle it the same as `default`*". Omitting `case 6` and letting default do it's magic, can be read months later as "*we/they only knew about 1-5 back then, are we sure 6 should be the same as default?*".  

I'm against commenting like `//case 6:\ndefault:` or anything else other than the above example, because the comments can be lost, misplaced, or just plain outdated, while having proper, compiling and linted code there makes anyone who edits/copy-pastes the code think about that known! [potential corner] case.

**Comment by jugglinmike** [comment] 2017-09-09 17:05
Thanks for the report. This looks like a duplicate of https://github.com/jshint/jshint/issues/3148, so I am closing it to keep the discussion organized.

You'll be happy to know that a fix has already landed in the `2.10` feature branch, so the behavior you're looking for will be available in the next minor release.

Though if you'll forgive the editorializing, I do believe your use case would be better served by through documentation explaining your intentions--that's a lot to infer from an empty `case` clause!

**Closed by jugglinmike** 2017-09-09 17:05 UTC
