### ISSUE TITLE
Can jshint warn when using deprecated options?

### ISSUE THREAD

**Issue by stevemao** [jshint/jshint#2245] opened 2015-03-09 03:15 UTC
For both cli and local package usage.

Currently users hardly notice if there is any option deprecated and jshint does not check against those options. It confuses users and if there is any problem with the deprecated option in the code, users might not know. Say user enables smart tabs but jshint does not throw any error and there might be mixed tabs and spaces.

**Comment by lukeapage** [comment] 2015-03-12 21:39
+1

**Comment by lukeapage** [comment] 2015-07-04 06:32
duplicate of #1346

**Closed by lukeapage** 2015-07-04 06:32 UTC
