### ISSUE TITLE
infinite loop on simple code and grunt

### ISSUE THREAD

**Issue by RemiBloch** [jshint/jshint#2823] opened 2016-01-04 09:51 UTC
Hello,

I'm running jshint on my code using grunt, everything run smoothly, i get my warnings, etc.. until i write the following piece of code (i simplified it obviously it does nothing special)

```javascript
var tmp = [];
var currentDate;

for(var index = 0; index < tmp; index++){
    if(currentDate)
}
```

jshint loops infinitely

Thanks in advance

**Comment by jugglinmike** [comment] 2016-01-04 15:41
I cannot reproduce this problem in the latest stable release of JSHint (2.8.0). Can you share which version of JSHint you are using? (Note that this is distinct from the Grunt plugin's version)

**Comment by RemiBloch** [comment] 2016-01-04 15:58
It's indeed 2.8.0.

Also, i'm writting the js in es6. It might come from that.

**Comment by jugglinmike** [comment] 2016-01-04 18:11
I can't reproduce this in JSHint 2.8.0:

    $ ./bin/jshint --version
    jshint v2.8.0
    $ ./bin/jshint -
    var tmp = [];
    var currentDate;

    for(var index = 0; index < tmp; index++){
        if(currentDate)
    }
    stdin: line 6, col 1, Expected an identifier and instead saw '}'.
    stdin: line 6, col 1, Expected an assignment or function call and instead saw an expression.
    stdin: line 6, col 2, Missing semicolon.
    stdin: line 4, col 41, Unmatched '{'.
    stdin: line 7, col undefined, Unrecoverable syntax error. (100% scanned).

    5 errors

Even with the `esnext` version enabled:

    $ ./bin/jshint -
    // jshint esnext: true
    var tmp = [];
    var currentDate;

    for(var index = 0; index < tmp; index++){
        if(currentDate)
    }
    stdin: line 7, col 1, Expected an identifier and instead saw '}'.
    stdin: line 7, col 1, Expected an assignment or function call and instead saw an expression.
    stdin: line 7, col 2, Missing semicolon.
    stdin: line 5, col 41, Unmatched '{'.
    stdin: line 8, col undefined, Unrecoverable syntax error. (100% scanned).

    5 errors

Can you experiment with your configuration to see if any values there are
necessary to trigger the stall?

**Comment by jugglinmike** [comment] 2016-01-16 22:42
We won't be able to help without more information. I'm going to close this, but we can re-open if/when we know more.

**Closed by jugglinmike** 2016-01-16 22:42 UTC
