### ISSUE TITLE
JSHint 2.9.1 hangs to validate big array

### ISSUE THREAD

**Issue by angelozerr** [jshint/jshint#2866] opened 2016-02-03 00:21 UTC
If you try to validate only the JavaScript file [nodejs-todo/blob/master/lib/words.js](https://github.com/amirrajan/nodejs-todo/blob/master/lib/words.js) which contains a big array, JSHint 2.9.1 hangs.

**Comment by jugglinmike** [comment] 2016-02-04 00:44
That's some big JavaScript file! JSHint isn't "hanging" *per se*, it's just doing its best to inspect over 3 megabytes of text.

Because the vast majority of the file is declarative data, my recommendation would be to move the array into a standalone JSON file. As a simple data interchange format, JSON does not have to be linted; validation is just a matter of parsing. And because there are no object literals in your data structure, you won't have to deal with the common annoyance of wrapping property names in quotation marks.

Maybe best of all, the 30 lines of executable code in the JavaScript file will be much easier to manage (both for JSHint and for your contributors).

**Comment by angelozerr** [comment] 2016-02-04 08:51
Many thanks @jugglinmike for your answer. In my case I use JSHint 2.9.1 to validate JavaScript file with Eclipse and the validation takes so long time with the validation of  [nodejs-todo/blob/master/lib/words.js](https://github.com/amirrajan/nodejs-todo/blob/master/lib/words.js) is done.

It seems this problem doesn't occur with old version of JSHint. For instance if you take the CodeMirror demo https://codemirror.net/demo/lint.html, which uses https://ajax.aspnetcdn.com/ajax/jshint/r07/jshint.js

There is not this problem: copy/paste content of  [nodejs-todo/blob/master/lib/words.js](https://github.com/amirrajan/nodejs-todo/blob/master/lib/words.js) in the first textarea and you will see that validation is fast.

**Comment by jugglinmike** [comment] 2016-02-07 21:44
Thanks for the background. I initially checked the behavior against `master`
and 2.8.0, but it looks like the performance drop occurred prior to that release
(813d97a8f5d96f2ab8320ad5da63662195f79d6c, to be exact).

I'm not ready to call this a regression, though. The problem here is that the
`[` token may signal the beginning of an array literal or an
AssignmentExpression using ES6 destructuring. For example, in a program like,

```js
var a = [
  // any amount of content
];
var b = [
  // any amount of content
] = anotherValue;
```

JSHint needs to make a decision between two very different parsing strategies
as soon as it encounters each `[`. To make this decision, it needs to traverse
the array pattern, and it may need to reach the very end to draw a conclusion.

We could try to detect things like IsValidSimpleAssignmentTarget for each
element, but that is very error-prone prior to parsing (e.g. `(function() {
/*anything*/ })().foo`). Of course, it wouldn't need to be perfect--even just
bailing in response to a literal value would probably be "good enough." The
problem there is that users who actually intended to use destructuring
assignment would receive warnings about invalid JSON instead of warnings about
invalid assignment targets.

Since programming errors related to destructuring assignment seem much more
common (especially given how new the language feature is) than the use case
here (linting very large array literals), I think optimizing for the latter
would do more harm than good.

**Comment by jugglinmike** [comment] 2016-02-27 20:42
It's been a few weeks, so since there are no objections, I'm closing this issue.

**Closed by jugglinmike** 2016-02-27 20:42 UTC

**Comment by angelozerr** [comment] 2016-02-27 21:22
@jugglinmike to be honnest with you, I'm not a big user of JSHint. I have reported this issue because of https://github.com/angelozerr/tern.java/issues/399

**Comment by orlandoibm** [comment] 2016-02-29 16:22
If I understand this correctly, it seems this is like we need to go in one of two different branches that are completely opposite. Given that, and understanding there are workarounds (and better coding standards to handle this in the first place), I am fine with closing it.

Just as a foot-note, it would be nice if this is documented somewhere, so people knows this scenario is currently unsupported and probably pointing them on possible solutions on their own code.

Thanks guys for your work on this.
Orlando
