### ISSUE TITLE
On Windows calling jshint from a script ends the script execution too

### ISSUE THREAD

**Issue by crystalfp** [jshint/jshint#2819] opened 2016-01-01 07:50 UTC
if you call jshint from a .BAT script, it executes but at the end it terminates also the calling script execution. This way you cannot put anything in the script after jshint invocation.
This is annoying especially if you run the script by double clicking on it in window explorer and want to see the results. Something along the lines of 
```
jshint --verbose --show-non-errors -c my.config my.js
pause
```
pause will never being executed, so the scripts window closes without a chance to see the results.
The problem happens also with a simple
```
jshint --version
pause
```
Thanks for considering.
Happy new year!
mario

**Comment by jugglinmike** [comment] 2016-01-09 01:41
Thanks for the report! I don't have a Windows machine handy at the moment, but I wonder if this has anything to do with [JSHint's use of `2` as a "error" exit code](https://github.com/jshint/jshint/blob/cfe6c43548debf11b4f7b4098d79a1316ca420a7/src/cli.js#L751). In that case, we could close this as a duplicate of https://github.com/jshint/jshint/issues/2672 . I'll wait until we're able to verify before closing.

**Comment by crystalfp** [comment] 2016-01-09 04:43
Hello!

Don't think exit(2) is the culprit.

After installing "exit" module (npm install exit)
I created the simple test:

exit.js:
var exit = require("exit");
console.log("Inside");
exit(2);

then the launch script exit.bat:
node exit.js
echo Outside

Executing the script prints correctly:
Inside
Outside

I think it is something related to a fork or something similar.

Thanks for the help!
				mario


On 09-Jan-16 02:41, jugglinmike wrote:
> Thanks for the report! I don't have a Windows machine handy at the
> moment, but I wonder if this has anything to do with JSHint's use of |2|
> as a "error" exit code
> <https://github.com/jshint/jshint/blob/cfe6c43548debf11b4f7b4098d79a1316ca420a7/src/cli.js#L751>.
> In that case, we could close this as a duplicate of #2672
> <https://github.com/jshint/jshint/issues/2672> . I'll wait until we're
> able to verify before closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jshint/jshint/issues/2819#issuecomment-170176945>.
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by crystalfp** [comment] 2016-01-09 04:47
Forgot.
Also using directly process.exit(2) gives the same result.
Thanks again!
			mario

On 09-Jan-16 02:41, jugglinmike wrote:
> Thanks for the report! I don't have a Windows machine handy at the
> moment, but I wonder if this has anything to do with JSHint's use of |2|
> as a "error" exit code
> <https://github.com/jshint/jshint/blob/cfe6c43548debf11b4f7b4098d79a1316ca420a7/src/cli.js#L751>.
> In that case, we could close this as a duplicate of #2672
> <https://github.com/jshint/jshint/issues/2672> . I'll wait until we're
> able to verify before closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jshint/jshint/issues/2819#issuecomment-170176945>.
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by duy-n** [comment] 2016-04-12 06:49
This sounds like a common Windows pitfall. Does the following fix your problem?

```
call jshint --version
pause
```

The reason is that the call to jshint actually calls `jshint.cmd`, which is (basically) another BAT file in your global NPM directory. When you invoke a BAT file from another BAT file, you have to prefix it with CALL or else the other BAT file replaces your current one, and you'll never execute any lines after it.

If this fixes your issue, then it's not a bug with jshint (or anything jshint can fix), just a quirk of Windows in general.

**Comment by jugglinmike** [comment] 2016-04-12 23:22
Thanks for the input, @duy-n! I have been trying to reproduce the bug from a virtual machine without any luck. I'll give this a shot next time I have access, though confirmation from @crystalfp would be ideal.

**Comment by crystalfp** [comment] 2016-04-13 02:06
Yes! This solved the problem.
Thanks a lot (and sorry to call it a jshint bug)

	mario

On 12-Apr-16 08:49, duy-n wrote:
> This sounds like a common Windows pitfall. Does the following fix your
> problem?
>
> |call jshint --version pause |
>
> The reason is that the call to jshint actually calls |jshint.cmd|, which
> is (basically) another BAT file in your global NPM directory. When you
> invoke a BAT file from another BAT file, you have to prefix it with CALL
> or else the other BAT file replaces your current one, and you'll never
> execute any lines after it.
>
> If this fixes your issue, then it's not a bug with jshint (or anything
> jshint can fix), just a quirk of Windows in general.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jshint/jshint/issues/2819#issuecomment-208734787>
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by jugglinmike** [comment] 2016-04-13 23:25
I'm glad we got to the bottom of this :) Thanks again, @duy-n

**Closed by jugglinmike** 2016-04-13 23:25 UTC

**Comment by SHocker-Yu** [comment] 2017-10-10 09:55
@duy-n Thank you very much! This question bothers me for a long time.
