### ISSUE TITLE
/* jshint ignore:start */  stopped working.

### ISSUE THREAD

**Issue by shreedharshetty** [jshint/jshint#2411] opened 2015-05-22 13:51 UTC
/* jshint ignore:start */
// jshint is throwing an error for the code present here.
/* jshint ignore:end */
till v2.5.11 it was working fine.

**Comment by jugglinmike** [comment] 2015-05-22 14:57
I can't reproduce this based on the information you've shared.

```js
/* jshint undef: true */

/* jshint ignore:start */
foo = 23;
sdflk;.fds.gsdf
/* jshint ignore:end */
```

    $ jshint gh-2411.js
    $ echo $?
    0
    $ jshint --version
    2.7.0

 [We maintain unit tests for the `ignore` directive](https://github.com/jshint/jshint/blob/2444a0463e1a99d46e4afa50ed934c317265529d/tests/unit/parser.js), so this may be an edge case. Can you provide some sample code?

**Comment by carlesandres** [comment] 2015-05-29 21:56
@jugglinmike : I have the same problem with this code:

```js
/*global $*/
/*jshint bitwise: false*/

angular.module('texto2App')
    .factory('utils', ['$rootScope', function utils($rootScope) {
    'use strict';

    // AngularJS will instantiate a singleton by calling "new" on this function

    /* jshint ignore:start */
    $.fn.extend({
        insertAtCaret: function(myValue){
            return this.each(function(i) {
                if (document.selection) {
                    //For browsers like Internet Explorer
                    this.focus();
                    var sel = document.selection.createRange();
                    sel.text = myValue;
                    this.focus();
                } else if (this.selectionStart || this.selectionStart == '0') {
                    //For browsers like Firefox and Webkit based
                    var startPos = this.selectionStart;
                    var endPos = this.selectionEnd;
                    var scrollTop = this.scrollTop;
                    this.value = this.value.substring(0, startPos)+myValue+this.value.substring(endPos,this.value.length);
                    this.focus();
                    this.selectionStart = startPos + myValue.length;
                    this.selectionEnd = startPos + myValue.length;
                    this.scrollTop = scrollTop;
                } else {
                    this.value += myValue;
                    this.focus();
                }
            });
        }
    });
    /*jshint ignore:end*/

    return {
        isInsertMode: function(){
            return !( $('#editorarea textarea').hasClass('normal') );
        },

        setNormalMode: function(){
            $('#editorarea textarea').addClass('normal');
        },

        setInsertMode: function(){
            $('#editorarea textarea').removeClass('normal');
        },

        getCursorPosition: function(){
            return $('#editorarea textarea')[0].selectionStart;
        },

        setCursorPosition: function(position){
            $('#editorarea textarea')[0].selectionStart = position;
        },

        findNext: function(pattern){
            // TO-DO This should be related to the editor.text from the model instead
            var text = $('#editorarea textarea').val();
            var currentPos = this.getCursorPosition();
            text = text.substring(currentPos);
            console.log(pattern);
            // TO-DO: Find regexp to locate position in a string
        },

        lightenColor: function(color, percent) {
            var isValidColor = /#[0-9A-Fa-f]{6}/.test(color);
            var num, amt, R, B, G;

            if (!isValidColor) {
                return false;
            }

            num = parseInt(color.slice(1),16);
            amt = Math.round(2.55 * percent);
            R = (num >> 16) + amt;
            B = (num >> 8 & 0x00FF) + amt;
            G = (num & 0x0000FF) + amt;

            return '#' + (0x1000000 + (R<255?R<1?0:R:255)*0x10000 + (B<255?B<1?0:B:255)*0x100 + (G<255?G<1?0:G:255)).toString(16).slice(1);
        },

        info: function(message, title, type){
            message = message || '';
            title = title || 'Info';
            type = type || 'info';

            var modalAttrs = { title: title, type: type, message: message };
            $rootScope.$emit('modal:show', modalAttrs);
        }
    };
}]);
```

My `.jshintrc` file is:
```
js
{
  "node": true,
  "browser": true,
  "esnext": true,
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "immed": true,
  "indent": 4,
  "latedef": true,
  "newcap": true,
  "noarg": true,
  "quotmark": "single",
  "regexp": true,
  "undef": true,
  "unused": true,
  "strict": true,
  "trailing": true,
  "smarttabs": true,
  "globals": {
    "angular": false,
    "describe": false,
    "it": false,
    "browser": false,
    "expect": false,
    "$": false
  },
  "expr": true
}
```

I am using `jshint v.2.7.0`.

Could you let me know how it works for you?

**Comment by jugglinmike** [comment] 2015-05-30 00:09
Thanks, @carlesandres. That could faithfully demonstrates the reported behavior, although I suspect it may be a different bug, since it occurs in 2.5.11 (and every commit since the introduction of the `ignore` directive, actually).

Reduced:

```js
void [function () {
  /* jshint ignore:start */
  ?
  /* jshint ignore:end */
}];
```

(`void` not strictly necessary, just need something to signal that the input is not JSON)

**Comment by carlesandres** [comment] 2015-05-31 21:34
@jugglinmike Many thanks for taking care of this.

**Comment by lukeapage** [comment] 2015-06-27 07:58
merged to master, will be in the release after the current 2.8.0

**Closed by lukeapage** 2015-06-27 07:58 UTC
Labels: P2
