### ISSUE TITLE
Two class functions before declaring class reports E056, but no report if only one function.

### ISSUE THREAD

**Issue by tpishi** [jshint/jshint#2886] opened 2016-03-04 13:09 UTC
jshint reports E056 in the following code.
```javascript
'use strict';
function foo() {
  Test.hello();
}
function bar() {
  Test.hello();
}
class Test {
  static hello() {
    console.log('Hello, world');
  }
}
```
But it does not report if Test.hello() is only one.
```javascript
'use strict';
function foo() {
  //Test.hello();
}
function bar() {
  Test.hello();
}
class Test {
  static hello() {
    console.log('Hello, world');
  }
}
```
.jshintrc is as follows
```javascript
{
  "esversion": 6,
  "node": true
}
```

**Comment by jugglinmike** [comment] 2016-03-04 14:49
Thanks for the report! This is a duplicate of gh-2838. The bug was fixed via gh-2842, and the fix will be available in the next (post-2.9.1) version of JSHint.

**Closed by jugglinmike** 2016-03-04 14:49 UTC
