### ISSUE TITLE
W codes

### ISSUE THREAD

**Issue by ekkis** [jshint/jshint#2817] opened 2015-12-30 01:01 UTC
running `jshint` produces something like:

> editor.js: line 132, col 27, Did you mean to return a conditional instead of an assignment? (W093)

where can I find a map of these "W" codes to the option names? couldn't we just include the option name in the error message (so I know what to turn off)?

**Comment by nicolo-ribaudo** [comment] 2015-12-30 08:57
You can find it here (but it is a little outdated):
https://jslinterrors.com/?linter=jshint

**Comment by jugglinmike** [comment] 2015-12-30 15:25
This information is not currently available. There is a long-standing feature request for that, though: https://github.com/jshint/jshint/issues/1270. This issue is essentially a duplicate of that one, so I'm going to close it.

**Closed by jugglinmike** 2015-12-30 15:25 UTC
