### ISSUE TITLE
Destructing operator hits parameter limit

### ISSUE THREAD

**Issue by duereg** [jshint/jshint#2183] opened 2015-02-18 19:46 UTC
With param limit set to 3:

let getResturants = ({page, pageSize, domain, metroId} = {}) => {
                              ^ This function has too many parameters. (4)

**Comment by mbildner** [comment] 2015-02-23 15:33
@duereg what is the expected behavior and what is actually happening?

**Comment by duereg** [comment] 2015-02-23 18:00
So a destructing operator is operating on a single parameter. So these code blocks are equivalent: 

```javascript
var foo = function(args) {
  var a = args.a;
  var b = args.b;
  var c = args.c;
}
```

```javascript
let foo = ({a, b, c}) => {
  //a,b,c are all available to this function, just like in the call above
}
```

I would expect this destructing operator would count as 1 param. 

It appears the current behavior is that every field destructed from the given object is counted as a param, instead of the whole object being counted as a param. 

In the examples above, jshint says the 1st example has 1 param, but the 2nd example has 3 params.

Does that make sense?

**Comment by mbildner** [comment] 2015-02-27 16:07
@duereg yup I definitely get the question. I'm looking through the spec to try to figure out what the correct behavior is. Conceptually it makes sense to me that since each param is usable on its own (ie not as a member of an object) that it should be counted for parameter length. With that said, I haven't found documentation to back up that feeling yet, so still looking.

**Comment by rwaldron** [comment] 2015-02-27 17:04
@duereg 

> It appears the current behavior is that every field destructed from the given object is counted as a param, instead of the whole object being counted as a param.

This is definitely a bug. 


@mbildner 

> since each param is usable on its own (ie not as a member of an object) that it should be counted for parameter length

This function defines only one formal parameter and expects only one argument: an object that will be destructured according to the object binding pattern defined in the single formal parameter: 

```js 
let foo = ({a, b, c}) => {
  //a,b,c are all available to this function, just like in the call above
};
foo.length === 1; // true
```

This function defines two formal parameters and expects two arguments: the first is an object that will be destructured according to the object binding pattern defined in the first formal parameter; the second is a non-specific that will be assigned to the simple formal parameter binding identifier:

```js 
let foo = ({a, b, c}, another) => {
  //a,b,c are all available to this function, just like in the call above
};
foo.length === 2; // true
```



http://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions-static-semantics-expectedargumentcount
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions-static-semantics-expectedargumentcount

**Comment by mbildner** [comment] 2015-02-27 17:54
@rwaldron aha thanks for the info and for the references! I'll start looking into a fix :)

**Closed** 2015-07-26 21:50 UTC
Labels: ES6, Has PR, P2
