### ISSUE TITLE
Support deconstruction of arrow function parameters

### ISSUE THREAD

**Issue by derwaldgeist** [jshint/jshint#3135] opened 2017-06-01 08:41 UTC
This does not work for me, although it is ES6 compliant and correctly transpiled by Babel:

```js
const f = ({x,y}) => {
   ... x and y can be referenced as parameters ...
}
```

jshint reports: `Unexpected token =>`

**Comment by jugglinmike** [comment] 2017-06-01 13:25
This is working as intended for me (omitting the invalid code on line 2, of course). Have you set the option `esversion` to `6`? That's currently a requirement for ES2015 code. If so, there may be something else going wrong--could you share the version of JSHint you are using in that case?

**Comment by derwaldgeist** [comment] 2017-06-04 18:28
Hi @jugglinmike Thanks for coming back to this. I have set "esnext: true". Maybe that's not enough? I am using the jshint version that comes with Atom's jshint package. Not sure which version this is.

**Comment by jugglinmike** [comment] 2017-06-04 18:49
Although we recommend `esversion: 6` over `esnext: true`, the latter is still technically supported. I can confirm expected behavior (i.e. successful parsing) even with `esnext: true` locally, so we'll need more information:

- The version of JSHint you are using (try using `npm ls` to find the version that's installed on your system)
- A standalone script (this should include all required linting options specified with an in-line comment)
- The full output

**Comment by derwaldgeist** [comment] 2017-06-04 19:12
I just looked into the Atom jshint repo:
https://github.com/Joezo/atom-jshint/blob/master/package.json
It's using jshint ^2.5.6
What do you mean by "standalone script" and "full output"? I am using jshint as part of the Atom jshint package, so linting is done in the background without any visible output despit the error message.

**Comment by jugglinmike** [comment] 2017-06-10 17:50
By "standalone script," I mean a valid JavaScript program that demonstrates the
issue, complete with the necessary JSHint configuration. (For more information,
check out the project's [contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md#bug-reports).)

By "full output", I mean the text returned by the JSHint program itself. As you
are using an editor plugin, this will require steps that are different from
your normal workflow, but it's the best way to isolate other factors that could
be contributing to the issue.

The dependency information for your plugin is only so helpful because it
specifies a range of possible versions. The version that is being run on your
system depends on when you installed the plugin and the dependencies of the
other Node.js modules in your project. I recommended using `npm ls` because
that will report the exact version as installed on your system.

Depending on the version of npm that you are using, the JSHint binary may be
available at `node_modules/.bin/jshint`. If so, you can use that to collect the
"full output" and also the version (via `./node_modules/.bin/jshint --version`.

**Comment by jugglinmike** [comment] 2017-09-09 17:11
We can't move forward on this without more information. Since it's been a few months we've heard from you, I'm going to close this issue for now. We can re-open if you or anyone else can follow up.

**Closed by jugglinmike** 2017-09-09 17:11 UTC
Labels: Needs Information

**Comment by derwaldgeist** [comment] 2017-09-09 17:18
Sorry, I switched to eslint now.
