### ISSUE TITLE
<!-- single line comments not lexed properly

### ISSUE THREAD

**Issue by MitalAshok** [jshint/jshint#3082] opened 2017-01-01 01:36 UTC
`<!--` is a HTML-like comment starts a single line comment (According to <http://www.ecma-international.org/ecma-262/6.0/#sec-html-like-comments>), but jshint throws around 5 warnings when it's used as one:

```
1	Expected an identifier and instead saw '<'.
1	Expected an operator and instead saw '!'.
1	Expected an operator and instead saw '--'.
1	Expected an assignment or function call and instead saw an expression.
1	Missing semicolon.
```
(This was from http://jshint.com/ with just the line `<!--`. It should throw no errors.)

They work like regular `//` comments: The line is ignored from the `<!--` upto, but not including, a line terminator (So it's just another single-line comment).

And for non-browser environments, in Node.js v7.3.0, the following file when run:

```javascript
<!-- console.log('Fail');
console.log('Pass');
```

only outputs `Pass`.

---

A fix to this would be adding these lines at line 492 in [/src/lex.js](https://github.com/jshint/jshint/blob/master/src/lex.js#L492):

```javascript
    // ...
      this.skip(2);
      return null;
    }

    // HTML-like comments start with <!-- and cause the line to be ignored upto the EOL
    if (ch1 === "<" && ch2 === "!" && this.peek(2) === "-" && this.peek(3) === "-") {
      this.skip(this.input.length);  // Skip to the EOL
      return commentToken("<!--", rest.substr(2));  // Remove the two -- characters in rest
    }

    // Comments must start either with // or /*
    if (ch1 !== "/" || (ch2 !== "*" && ch2 !== "/")) {
      return null;
    }
    // ...
```
This has the side effect that `<!--` will allow members and globals comments without the qualifying `<!-- jshint: `.

([Current revision of lex.js](https://github.com/jshint/jshint/blob/b646aeae63f49a24e649a86dbc8d94c20d57f38c/src/lex.js#L492))

**Comment by nicolo-ribaudo** [comment] 2017-01-03 17:31
This is a duplicate of #1256

If @jshint members agree, I think you could create a pr containing the fix, but it should be enabled by an opt-in option (something like `htmlcomments`)

**Comment by jugglinmike** [comment] 2017-01-15 20:50
Thanks for the report (and the patch)! Closing as duplicate of gh-1256.

**Closed by jugglinmike** 2017-01-15 20:50 UTC
