### ISSUE TITLE
Setting "latedef" to "nofunc" no longer ignores function declarations

### ISSUE THREAD

**Issue by gilluminate** [jshint/jshint#2833] opened 2016-01-19 19:49 UTC
Setting "latedef" to "nofunc" as described here:
http://jshint.com/docs/options/#latedef

is no longer working in 2.9.1. Had to revert to 2.8.0 to stop getting "xxx was used before it was defined" errors on functions.

**Comment by thomas658** [comment] 2016-01-20 14:54
similar problem with this code:
```javascript
/*jshint latedef:nofunc */
function a() {
  function b(x) {
    return x + y;
  }
  var y = 5;
  return b(2);
}
```
complains with
One warning
6	'y' was used before it was defined.

Is the behaviour intended?
Searches for 'nofunc' in the jshint script sources shows up just the option validation.

**Comment by nicolo-ribaudo** [comment] 2016-01-21 21:17
@gilluminate Can you provide an example? I can't reproduce the issue using this code:
```js
/* jshint latedef: nofunc */

a();
function a() {}
```

@thomas658 `latedef: nofunc` allows you to define functions after their usage. You are using a variable (`y`) before declaring it.

**Comment by gamebox** [comment] 2016-01-29 22:29
I have code similar to this

`var b = function() {
  a()
};

var a = function() {...};
a();`

And am getting the error thrown at the line where `a` is defined.  Even with `/* jshint -W003 */` at the top of the file

**Comment by gilluminate** [comment] 2016-01-30 02:23
@nicolo-ribaudo the problem arises with:

```
/* jshint latedef: nofunc */

a();
function a() {}

var b = c;
var c = function(){};
```

Which complains that `'c' was used before it was defined.`

'c' was also ignored in version 2.8.0

**Comment by nicolo-ribaudo** [comment] 2016-01-30 03:37
The docs say:
> Setting this option to "nofunc" will allow function **declarations** to be ignored.

`c` is a function expression: you can't use `c` before the `var c ...` line (if you write `console.log(b)` you will get `undefined`)

**Comment by gilluminate** [comment] 2016-02-01 16:48
Ok, I understand. Does that mean it wasn't working as designed in 2.8.0?

**Comment by nicolo-ribaudo** [comment] 2016-02-01 18:15
> Does that mean it wasn't working as designed in 2.8.0?

I get the `'c' was used before it was defined` warning also in 2.8.0

```
nicol@DESKTOP-EDGLMME ~/documents/JSHint
$ bin/jshint --version
jshint v2.8.0

nicol@DESKTOP-EDGLMME ~/documents/JSHint
$ cat demo.js
/* jshint latedef: nofunc */

a();
function a() {}

var b = c;
var c = function(){};

nicol@DESKTOP-EDGLMME ~/documents/JSHint
$ bin/jshint demo.js
demo.js: line 7, col 7, 'c' was used before it was defined.

1 error
```

**Comment by gilluminate** [comment] 2016-02-01 20:17
Strange. For me as long as I have v2.8.0 installed I don't get an error. No matter, I'm going to update our code to resolve. Thanks for looking into it!

**Comment by jonathanbruder** [comment] 2016-02-12 23:33
There are a few different cases where changes to latedef are throwing, with or without latedef:'nofunc', using 2.9.1:

**Simple Rearrangements**

Starting with the most basic example:

````
    var x = function(){j();}
        , j = function(){console.log('in j');};
````

Which yields
````
   6 |        , j = function(){console.log('in j');};
                   ^ 'j' was used before it was defined.
````

**Cyclical relationships**

Sometimes cyclical relationships can't be untangled. Here are all six possible sequences of a triplet of entangled functions: 

```
    var a1 = function(){b1();}
        , b1 = function(){c1();}
        , c1 = function(){a1();};

    var a2 = function(){b2();}
        , c2 = function(){a2();}
        , b2 = function(){c2();};

    var b3 = function(){c3();}
        , a3 = function(){b3();}
        , c3 = function(){a3();};

    var b4 = function(){c4();}
        , c4 = function(){a4();}
        , a4 = function(){b4();};

    var c5 = function(){a5();}
        , a5 = function(){b5();}
        , b5 = function(){c5();};

    var c6 = function(){a6();}
        , b6 = function(){c6();}
        , a6 = function(){b6();};
````

Yields:

````
      7 |        , b1 = function(){c1();}
                   ^ 'b1' was used before it was defined.
      8 |        , c1 = function(){a1();};
                   ^ 'c1' was used before it was defined.
     12 |        , b2 = function(){c2();};
                   ^ 'b2' was used before it was defined.
     16 |        , c3 = function(){a3();};
                   ^ 'c3' was used before it was defined.
     19 |        , c4 = function(){a4();}
                   ^ 'c4' was used before it was defined.
     20 |        , a4 = function(){b4();};
                   ^ 'a4' was used before it was defined.
     23 |        , a5 = function(){b5();}
                   ^ 'a5' was used before it was defined.
     24 |        , b5 = function(){c5();};
                   ^ 'b5' was used before it was defined.
     28 |        , a6 = function(){b6();};
                   ^ 'a6' was used before it was defined.
````


**Reflective references:**

I'm also seeing this in function factories which, without addressing code style, are completely legal javascript: 

````
 var ExtensibleFunction = function(){/*do something with passed value*/}
        , Factory = function(){
            var injector;
            injector = $.extend(function(){return ExtensibleFunction.apply(injector, arguments);}, prototypeProxy);
            return injector;
        }
        , prototypeProxy = {
            constructor: Factory
            , chainableMethod: function(){}
        };


    var product = new Factory();

    product('product key').chainableMethod();

````

Which yields:

````
12 |        , prototypeProxy = {
                   ^ 'prototypeProxy' was used before it was defined.
````

Of course, in this case, switching the order doesn't solve for the problem:

````
  var ExtensibleFunction = function(){/*do something with passed value*/}
        , prototypeProxy = {
            constructor: Factory
            , chainableMethod: function(){}
        }
        , Factory = function(){
            var injector;
            injector = $.extend(function(){return ExtensibleFunction.apply(injector, arguments);}, prototypeProxy);
            return injector;
        };



    var product = new Factory();

    product('product key').chainableMethod();
````

Yields: 

````
     11 |        , Factory = function(){
                   ^ 'Factory' was used before it was defined.
````

Ultimately, the tool creates the situation where it becomes more acceptable to do something like this: 

````
var prototypeProxy
        , ExtensibleFunction = function(){/*do something with passed value*/}
        , Factory = function(){
            var injector;
            injector = $.extend(function(){return ExtensibleFunction.apply(injector, arguments);}, prototypeProxy);
            return injector;
        };

    prototypeProxy = {
        constructor: Factory
        , chainableMethod: function(){}
    };
````

**Comment by gilluminate** [comment] 2016-02-15 19:06
@jonathanbruder I think all of these can be answered by the same answer that @nicolo-ribaudo gave us here https://github.com/jshint/jshint/issues/2833#issuecomment-173710334

Those are all variables declarations (where the variable is set to a function) not function declarations.

**Comment by gamebox** [comment] 2016-02-17 00:57
I'm not sure that covers the use case I described.  My issue is there is a call to a function inside an earlier functions definition.  The earlier function that calls the later function is not being called before the later function has been defined. again,

`var a = function() { b(); }; var b = function() {};`

The error is thrown where `b` is called, but `a` has not been called yet, so the definition of the function should not matter, only that it is defined within the scope.

**Comment by jonathanbruder** [comment] 2016-02-17 03:00
@gilluminate, I appreciate that your are being helpful, and that you are technically correct. But even if the issue as titled doesn't exist, the issue as described is a definite break in backwards compatibility over 2.8.0, and it is very similar in form to #2628. @gamebox and I are describing the same case. latedef exists to prevent issues caused by hoisting, but incorrectly identifies the sequence of use in inner function scopes (_not_ block scopes.) My examples demonstrate common patterns that passed in 2.8.0.

**Comment by jugglinmike** [comment] 2016-02-21 19:48
First off, for anyone following along, you have **two options for immediate
fixes** that are guaranteed to be compatible regardless of the decision here:

1. Disable `latedef`
2. Explicitly hoist the offending variable declarations (which, depending on
   the relationships, may involve splitting declaration from assignment).

It looks like the issue here is that version 2.9.1 made previously-inconsistent
behavior consistent, specifically as it relates to the global scope of the
input code. Here's an example:

```js
/*jshint latedef: true */

(function() {
  (function() {
    void fnScope_innerScope;
  }());
  void fnScope_sameScope;
  var fnScope_innerScope, fnScope_sameScope;
}());

(function() {
  void globalScope_innerScope;
}());
void globalScope_sameScope;
var globalScope_innerScope, globalScope_sameScope;
```

JSHint 2.8.0 reports:

    ../playground/gh-2833.js: line 8, col 44, 'fnScope_sameScope' was used before it was defined.
    ../playground/gh-2833.js: line 15, col 27, 'globalScope_innerScope' was used before it was defined.
    ../playground/gh-2833.js: line 15, col 50, 'globalScope_sameScope' was used before it was defined.
    
    3 errors

JSHint 2.9.1, on the other hand, reports:

    ../playground/gh-2833.js: line 8, col 7, 'fnScope_innerScope' was used before it was defined.
    ../playground/gh-2833.js: line 8, col 27, 'fnScope_sameScope' was used before it was defined.
    ../playground/gh-2833.js: line 15, col 5, 'globalScope_innerScope' was used before it was defined.
    ../playground/gh-2833.js: line 15, col 29, 'globalScope_sameScope' was used before it was defined.
    
    4 errors

@jonathanbruder For me, both versions of JSHint generate the same warnings for
the first two examples you shared ("Simple Rearrangements" and "Cyclical
relationships"). I'm wondering if they omit a function closure (the reported
warning line numbers suggest the presence of additional code, and the
indentation suggests that this is some sort of wrapping scope).

The documentation for this option has remained consistent across releases:

> This option prohibits the use of a variable before it was defined.

Because the more strict behavior is consistent with that description, we could
label this as a bug fix, not a regression, and close the issue.

That said, I get the sense that some folks in this discussion believe the
underlying behavior to be incorrect. After all, in many of the examples shared
so far, there doesn't seem to be anything dangerous about the pattern. JSHint
could be more lax about enforcing the `latedef` option, allowing "early"
references to variables within nested functions.

I'm not so sure about this. On the one hand, the intent of the option is pretty
clear, and the strict interpretation fits. On the other hand, I personally
don't find this option particularly useful to begin with--what kind of bugs
could result from relying on variable hoisting? So I may not be the best judge
of how it could be improved.

If you'd like to make a case for implementing the more lax behavior, please do
so in the next few days. Otherwise, I'll plan on closing this issue as "not a
bug."

**Comment by jugglinmike** [comment] 2016-03-27 23:30
Since it's been over a month without suggestion for an alternative, I'm going to close this issue.

**Closed by jugglinmike** 2016-03-27 23:30 UTC
