### ISSUE TITLE
ES6 Destructuring / default arguments

### ISSUE THREAD

**Issue by vitch** [jshint/jshint#2746] opened 2015-11-05 15:08 UTC
The following code:

```
function add({a=1, b=2} = {}) {
  return a + b;
}
add({a: 2}); // 4
```

Results in JSHint complaining: 

> Expected ',' and instead saw '='.
> Expected an identifier and instead saw '1'.
> Expected ',' and instead saw '='.
> Expected an identifier and instead saw '2'.

The code is valid and gets transpiled successfully by Babel.

Apologies if this is already reported, I couldn't find anything in a search of the issues

**Comment by nicolo-ribaudo** [comment] 2015-11-05 15:12
Duplicate of #1941 and fixed on master.

**Closed** 2015-11-05 15:20 UTC

**Comment by vitch** [comment] 2015-11-05 15:24
Thanks and sorry for the noise...
