### ISSUE TITLE
JSHint reporting warnings disabled using /* jshint -Wxyz */

### ISSUE THREAD

**Issue by NicolaOrritos** [jshint/jshint#3134] opened 2017-05-31 14:08 UTC
Here's the code that generates the warning (but it shouldn't):
```js
class Group {
    // ...

    /* jshint -W098 */
    set name(value) {
        // Nothing happens: after initialization this property is immutable
    }
    /* jshint +W098 */

    // ...
}
```

And the output of jshint:
```Bash
$ jshint src/server/lib/group.js --verbose
src/server/lib/group.js: line 46, col 14, 'value' is defined but never used. (W098)

1 error

$ jshint --version
jshint v2.9.4
```

**Comment by jugglinmike** [comment] 2017-06-03 17:18
I'm not able to reproduce this behavior locally. I had to add some in-line configuration to your demo script:

    // jshint esversion: 6, unused: true
    class Group {
        // ...

        /* jshint -W098 */
        set name(value) {
            // Nothing happens: after initialization this property is immutable
        }
        /* jshint +W098 */

        // ...
    }

But for me, JSHint version 2.9.4 reports the following:

    gh-3134.js: line 6, col 9, Setter is defined without getter. (W078)

The line numbers in your output don't match the demo, so I'm wondering if there are other factors at play. Could you share a script that demonstrates the bug when pasted into the editor on http://jshint.com ?

**Comment by NicolaOrritos** [comment] 2017-06-05 08:41
Well, things just got more complicated.
The following code DOESN'T trigger the warning on the JSHint online editor, but it should:
```js
/* jshint esversion: 6, asi:true, node:true */

class Group
{
    constructor(name)
    {
        this._name = name
    }

    get name()
    {
        return this._name
    }
    
    set name(value)
    {
        // Nothing happens: after initialization this object is immutable
    }
}

module.exports = Group
```
I completed the code sample with the parts that I left out for simplicity before.

**Comment by jugglinmike** [comment] 2017-06-05 13:52
That is expected. There is a syntactic requirement for "set" accessors function to have a parameter, so JSHint doesn't warn if that parameter is unused (since there is no alternative for use cases like yours).

This behavior is distinct from what you originally reported, so I don't want to close this issue prematurely. Can you verify that your problem is resolved?

**Comment by NicolaOrritos** [comment] 2017-06-05 15:17
No, it isn't.
I pointed out the new behavior because I thought it was related to my initial report somehow. If it confuses you just let it go and let's return to the core of the problem: I have a warning on that `value` parameter saying it's defined but never used (W098) and it's not silenced by using `/* jshint -W098 */`.
Also: running JSHint from the command line I experience the error, submitting my code to the JSHint online editor I don't.
I simply installed jshint from npm like this: `npm install jshint`.

**Comment by jugglinmike** [comment] 2017-06-10 17:59
No confusion, just trying to stay organized. One bug report per bug, ya know? Since that second behavior isn't a bug, I agree that it's best to move on.

I still can't reproduce the original problem, though. Does the script I shared in [my previous comment](https://github.com/jshint/jshint/issues/3134#issuecomment-305988935) produce a warning on your end? If not, then there is likely some important detail missing from the original report. For instance, there may be some configuration in a local `.jshintrc` file that needs to be set.

**Comment by jugglinmike** [comment] 2017-09-09 17:12
We can't move forward on this without more information. Since it's been a few months we've heard from you, I'm going to close this issue for now. We can re-open if you or anyone else can follow up.

**Closed by jugglinmike** 2017-09-09 17:12 UTC
Labels: Needs Information
