### ISSUE TITLE
Exported var was used before it was defined in 2.9.0

### ISSUE THREAD

**Issue by robrich** [jshint/jshint#2662] opened 2015-09-03 20:30 UTC
Using JSHint 2.9.0, I get this error:  `common-lib.js: line 2, col 5, 'commonLib' was used before it was defined.` and in previous versions of JSHint I did not.  Moving the `/* exported ... /*` line to the end of the file resolves the symptom.  Here is a minimum sample repro project:

.jshintrc:
```
{
  "latedef": true
}
```

common-lib.js:
```
/* exported commonLib */
var commonLib = (function () {
  'use strict';

  return 'the common lib';
}());
```

command I run:
`jshint .`

**Comment by nicolo-ribaudo** [comment] 2015-09-03 21:37
Possible duplicate of gh-2658

**Comment by nicolo-ribaudo** [comment] 2015-09-04 13:15
The regression has been introduced in 08eb4e25962eb71f94c09f79b3b08288b91a7bce

**Comment by lukeapage** [comment] 2015-09-04 15:33
@nicolo-ribaudo please comment if you are working on a fix and I won't start working on one..

**Comment by lukeapage** [comment] 2015-09-04 16:59
Assuming not..

**Comment by nicolo-ribaudo** [comment] 2015-09-04 17:09
I'm sorry I didn't see you comment... Have you already started working on this?

**Comment by lukeapage** [comment] 2015-09-04 17:24
I've started trying to think of the best solution..  the easy thing is to
not warn latedef when no usages have tokens..  or have a flag for a non
export directive on the usage state.. alternatively don't use usages, but
then we have to resolve the export directive to the right scope...

Those are my thoughts so far.  I am running out of time today though so go
ahead if you have started or have an idea..

**Comment by lukeapage** [comment] 2015-09-04 17:27
I would probably try the flag route..  so non directive exports set
usages.codeUsage or something like that and latedef checks that. but you
might have a better idea...

**Comment by nicolo-ribaudo** [comment] 2015-09-04 17:32
> Those are my thoughts so far.  I am running out of time today though so go
ahead if you have started or have an idea..

I have a fix which is almost working... (It just has a bug when exporting variables defined using `/* globals`)

**Comment by lukeapage** [comment] 2015-09-04 17:40
go ahead, I will look at the PR.

**Closed** 2015-09-13 07:10 UTC
Labels: Has PR, Regression
