### ISSUE TITLE
Allow multiple reporters for a single configuration

### ISSUE THREAD

**Issue by aryantutor** [jshint/jshint#2872] opened 2016-02-10 05:30 UTC
Anyone knows how to use multiple reporter for single configuration.

**Comment by nicolo-ribaudo** [comment] 2016-02-10 16:06
This feature has been proposed in #2727

**Comment by jugglinmike** [comment] 2016-02-14 22:06
Although you may not need a new feature at all--see [this comment in the original feature request](https://github.com/jshint/jshint/issues/1702#issuecomment-183145400). In any event, this is a duplicate of gh-1702, so let's track it there.

**Closed by jugglinmike** 2016-02-14 22:06 UTC
