### ISSUE TITLE
node:true setting is not honored anymore in 2.9.1 ?

### ISSUE THREAD

**Issue by amrish7** [jshint/jshint#2835] opened 2016-01-19 23:23 UTC
jshint has started complaining about `Missing "use strict" statement` on all the `index.js` files in my node project files after upgrading to `jshint@2.9.1` from `jshint@2.8.0`. 

I do have `"node": true,` set in my `.jshintrc` file and as per the [documentation] (http://jshint.com/docs/options/#node), jshint should not complain about *absence of* **(edit)** file level `use strict` pragma which would apply to node. 

Wondering if something broke?

**Comment by jugglinmike** [comment] 2016-01-20 00:33
I'm a little confused about the problem; can you help me understand? In the first paragraph, you mention the "Missing 'use strict' statement" warning--that would be triggered in the *absence* of a "use strict" directive. The second paragraph references the file-level "use strict" directive--that would be triggered in the *presence* of the directive.

Maybe the best way to explain would be to share some sample code that triggers the warning(s). To make reproducing the problem easier, please include the necessary configuration as inline directives (e.g. `// jshint node: true`).

**Comment by amrish7** [comment] 2016-01-20 00:39
Sorry about the confusion, what I actually wanted to mean in the 2nd paragraph was

**Comment by amrish7** [comment] 2016-01-20 00:44
Sorry about the confusion, what I actually wanted to say was - jshint is complaining about missing `use strict` statements from my node project's `index.js` file after upgrading to 2.9.1. I will share the code dump shortly

**Comment by amrish7** [comment] 2016-01-20 01:15
I have created https://github.com/amrish7/jshint-failure explaining the issue that I am running into. After upgrading to `jshint@2.9.1`, node.js entry files like `index.js` that do not have a function were getting penalized for missing `use strict` statements

**Comment by jugglinmike** [comment] 2016-01-20 01:41
Thanks for taking the time to put that together! This is indeed a regression. Here's a simplified test case:


```js
// jshint node: true, strict: true, globalstrict: true

x();
```

(Note that if the file contains a Statement, it would trigger a warning in JSHint 2.8.0. This means the regression is limited to files that contain only ExpressionStatements like the one above.)

We'll get right on this!

**Comment by jugglinmike** [comment] 2016-01-20 01:54
I may have spoken too soon on this one. Although the warning is definitely new,
it is actually in-line with the 2.8.0 documentation. Here's what it had to say
about `strict`:

> This option requires all functions to run in ECMAScript 5's strict mode.
> [Strict mode](https://developer.mozilla.org/en/JavaScript/Strict_mode) is a
> way to opt in to a restricted variant of JavaScript. Strict mode eliminates
> some JavaScript pitfalls that didn't cause errors by changing them to produce
> errors.  It also fixes mistakes that made it difficult for the JavaScript
> engines to perform certain optimizations.
>
> *Note:* This option enables strict mode for function scope only. It
> *prohibits* the global scoped strict mode because it might break third-party
> widgets on your page. If you really want to use global strict mode, see the
> *globalstrict* option.

...and here's the documentation of `globalstrict`:

> This option suppresses warnings about the use of global strict mode.  Global
> strict mode can break third-party widgets so it is not recommended.
>
> For more info about strict mode see the `strict` option.

...and (finally) this is what the docs had to say about `node`:

> This option defines globals available when your code is running inside of the
> Node runtime environment. [Node.js](http://nodejs.org/) is a server-side
> JavaScript environment that uses an asynchronous event-driven model. This
> option also skips some warnings that make sense in the browser environments
> but don't make sense in Node such as file-level `use strict` pragmas and
> `console.log` statements.

So, according to that information, a file like this:

```js
// jshint node strict: true, globalstrict: true, node: true
module.exports = {};
```

...should have been warning all along because the code is not in strict mode.
By failing to emit a warning, JSHint was contradicting its own documentation.
This means the new error is actually a result of a bug fix, not a regression.

**Comment by amrish7** [comment] 2016-01-20 02:26
as per the documentation on `node` - `...This
option also skips some warnings that make sense in the browser environments
but don't make sense in Node such as file-level use strict pragmas and
console.log statements.` 

Does it mean that setting `node` to `True` would ask jshint to **not** complain on omitting file level `use strict` (as in my example)?

**Comment by jugglinmike** [comment] 2016-01-20 02:40
By default, JSHint issues a warning when it encounters a global "use strict" directive. When either the `node` option or the `globalstrict` option is set, that warning is disabled. (That is the behavior described by the documentation you've quoted.) Setting either is equivalent to saying, "It is safe for my code to use a global `"use strict"` directive."

Separately, JSHint has the capability of *requiring* that code is in strict mode. This is enabled with `strict: true`. Setting this is equivalent to saying, "I want as much code as possible to be in strict mode."

Setting `strict: true, globalstrict: true` is equivalent to saying, "I want all linted files to declare a `"use strict";` directive as the first statement."

**Comment by jugglinmike** [comment] 2016-04-23 16:16
In the absence of any objection, I'm going to remove the "regression" label and close this issue.

**Closed by jugglinmike** 2016-04-23 16:16 UTC
