### ISSUE TITLE
Processing of large scripts takes very long (starting with release 2.6.1)

### ISSUE THREAD

**Issue by rondonjon** [jshint/jshint#2532] opened 2015-07-07 11:15 UTC
I am working with Javascripts for single-page apps which have concatenated sizes of 400kb-800kb.

Using releases until 2.5.11, processing of these scripts takes approx. 2 seconds on an average PC.

In later releases, jshint needs up approx. 30 seconds to process the same scripts, which makes it unusable in frequently executed development builds.

**Comment by lukeapage** [comment] 2015-07-07 11:49
The tests seem to run faster in 2.6.1 than in 2.5.11, so I don't think there is any obvious speed issue. Its possible of course that something in your scripts or the size of them is causing an issue. Have you considered linting the non-concatenated scripts?

Is it 2.6.0 that jshint becomes slow? What version of node are you running? Has anything else changed or is the *only* moving variable jshint?

Can you provide a test file? if not, would you be able to narrow down the commits - https://github.com/jshint/jshint/releases/tag/2.6.0 you should be able to install a particular git commit hash from inside npm.

**Comment by rondonjon** [comment] 2015-07-07 12:38
Luke, my apologies for the confusion. After running tests in even smaller version steps (see below) it seems that **the 2.6.0 release is still OK and the problem starts with 2.6.1.**

---

Now to your questions.

I am using node.js version 0.10.26, executed from within (node)eclipse.

jshint is indeed the only variable. I have tested several releases of jshint by exchanging the version numbers in the `package.json` files of my projects, wiping the node_modules, re-running npm install, and then executing the build. I believe the results speak for themselves.

Here is the setup for the following results:

```
	var srcFile = path.resolve(path.join(__dirname, "../_out/tmp/concat.js")),
		src = fs.readFileSync(srcFile).toString();
	
	var jsHintOptions = {
		node: true,
		freeze: true,
		notypeof: true,
		es3: false,
		es5: false,
		noarg: true,
		nocomma: false,
		multistr: false,
		debug: true,
		boss: false,
		evil: false,
		sub: true,
		undef: true,
		browser: true
	};
	
	var before = new Date().getTime();
	hint(src, jsHintOptions);
	var after = new Date().getTime();
	console.log("jshint took " + (after-before) + " ms");
```

After several iterations, I have now got the following numbers:

`"=2.5.11"` in `package.json`: `jshint took 1568 ms`
`"=2.6.0"` in `package.json`: `jshint took 1576 ms`
`"=2.6.1"` in `package.json`: `jshint took 177234 ms`
`"=2.6.2"` in `package.json`: `jshint took 98255 ms`
`"<2.7.0"` (resolves to `2.6.3`) in `package.json`: `jshint took 97844 ms`
`"=2.7.0"` in `package.json`: `jshint took 151964 ms`
`"*"` in `package.json`: `jshint took 99499 ms`

The size of the input file is 452,523 bytes. I cannot upload it here (company rules), but I can say that it has been generated with webpack, consists of 27 modules, and includes jQuery and backboneJs in their latest revisions. All jshints are currently failing with too many errors (~ 45-50% processed), with the vast majority of them being related to the aforementioned third-party modules.

**Comment by lukeapage** [comment] 2015-07-07 15:59
> I cannot upload it here (company rules), but I can say that it has been generated with webpack, consists of 27 modules, and includes jQuery and backboneJs in their latest revisions. 

We lint jQuery as part of our tests (the ones that don't increase in time between 2.6.0 and 2.6.1)

> All jshints are currently failing with too many errors (~ 45-50% processed), with the vast majority of them being related to the aforementioned third-party modules.

Its an alarm bell if its failing with alot of errors (it potentially makes the exact situation harder to reproduce). Would it be easy for you to make a bundle with just 3rd party modules? if that reproduces the issue, I assume it would be okay to give us that file and it will be alot easier?

**Comment by rondonjon** [comment] 2015-07-08 14:56
I have reduced the main JS file as follows:

```
"use strict";

require("jquery");
require("backbone");
require("../style/urw_gothic_l_book.css");
require("../style/urw_gothic_l_demi.css");
require("../style/urw_gothic_l_demi.css");
require("../style/droid_sansregular.css");
```

This results in the following webpack output:

```
Hash: 348abbeb2db180999732
Version: webpack 1.10.1
Time: 933ms
                                 Asset     Size  Chunks             Chunk Names
 8ca6e243b6a55cae710739a0f7aff3c7.woff    26 kB          [emitted]  
  fa40c1f01e7a257d9ec200925f173201.eot  23.2 kB          [emitted]  
 a7c5b2861afe11965cbac8e2cad7f3bb.woff  26.4 kB          [emitted]  
  a1ff28a4775f233223b49b3b098e1a79.ttf  46.7 kB          [emitted]  
  d5b4083c3ec24c7a37460e236e4b0238.svg  88.8 kB          [emitted]  
  666ce7af6532e896f2c1cf36f65b6c2b.eot  22.8 kB          [emitted]  
f62e04cebcac838736d81faa29443aba.woff2  20.3 kB          [emitted]  
acad91e3ba5a2e23d201c21af35316d3.woff2  20.6 kB          [emitted]  
  43a5620caadbd47ca093dd49e13270c2.ttf  46.1 kB          [emitted]  
  e46d257625f635231d4cbfe03a2d0cb8.svg  90.2 kB          [emitted]  
 a4068692facb5110970b29a0a5ada6d5.woff  17.3 kB          [emitted]  
  72519b3b5f3edf345a512da6212434ff.eot  15.4 kB          [emitted]  
  c3ea7a86e018a5e3860bc54b4017fb8f.ttf    28 kB          [emitted]  
  762d8dca9d10e3637fb7d8f270e08e25.svg  58.3 kB          [emitted]  
                          ../concat.js   400 kB       0  [emitted]  main
chunk    {0} ../concat.js (main) 386 kB [rendered]
    [0] ../src/js/3p.js 227 bytes {0} [built]
    [1] ../src/style/urw_gothic_l_demi.css 955 bytes {0} [built]
    [2] ../~/css-loader!../src/style/urw_gothic_l_demi.css 930 bytes {0} [built]
    [3] ../~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [4] ../src/font/urw_gothic_l_demi/urw_gothic_l_demi-webfont.eot 81 bytes {0} [built]
    [5] ../src/font/urw_gothic_l_demi/urw_gothic_l_demi-webfont.woff2 83 bytes {0} [built]
    [6] ../src/font/urw_gothic_l_demi/urw_gothic_l_demi-webfont.woff 82 bytes {0} [built]
    [7] ../src/font/urw_gothic_l_demi/urw_gothic_l_demi-webfont.ttf 81 bytes {0} [built]
    [8] ../src/font/urw_gothic_l_demi/urw_gothic_l_demi-webfont.svg 81 bytes {0} [built]
    [9] ../~/style-loader/addStyles.js 6.09 kB {0} [built]
   [10] ../~/jquery/dist/jquery.js 248 kB {0} [built]
   [11] ../~/backbone/backbone.js 70.9 kB {0} [built]
   [12] ../~/backbone/~/underscore/underscore.js 52.9 kB {0} [built]
   [13] ../src/style/urw_gothic_l_book.css 955 bytes {0} [built]
   [14] ../~/css-loader!../src/style/urw_gothic_l_book.css 930 bytes {0} [built]
   [15] ../src/font/urw_gothic_l_book/urw_gothic_l_book-webfont.eot 81 bytes {0} [built]
   [16] ../src/font/urw_gothic_l_book/urw_gothic_l_book-webfont.woff2 83 bytes {0} [built]
   [17] ../src/font/urw_gothic_l_book/urw_gothic_l_book-webfont.woff 82 bytes {0} [built]
   [18] ../src/font/urw_gothic_l_book/urw_gothic_l_book-webfont.ttf 81 bytes {0} [built]
   [19] ../src/font/urw_gothic_l_book/urw_gothic_l_book-webfont.svg 81 bytes {0} [built]
   [20] ../src/style/droid_sansregular.css 955 bytes {0} [built]
   [21] ../~/css-loader!../src/style/droid_sansregular.css 785 bytes {0} [built]
   [22] ../src/font/droid_sansregular/DroidSans-webfont.woff 82 bytes {0} [built]
   [23] ../src/font/droid_sansregular/DroidSans-webfont.eot 81 bytes {0} [built]
   [24] ../src/font/droid_sansregular/DroidSans-webfont.ttf 81 bytes {0} [built]
   [25] ../src/font/droid_sansregular/DroidSans-webfont.svg 81 bytes {0} [built]
```

The generated output file (~ 399 kb) is here (please download, paste expires in 1mo):
http://pastebin.com/eBiaWnZg

jshint 2.6.1 needs 109876 ms to analyze the file and terminates with the following output:

```
157:84: Missing semicolon. (code W033)
  >> 	module.exports = __webpack_require__.p + "fa40c1f01e7a257d9ec200925f173201.eot"
163:86: Missing semicolon. (code W033)
  >> 	module.exports = __webpack_require__.p + "acad91e3ba5a2e23d201c21af35316d3.woff2"
169:85: Missing semicolon. (code W033)
  >> 	module.exports = __webpack_require__.p + "a7c5b2861afe11965cbac8e2cad7f3bb.woff"
175:84: Missing semicolon. (code W033)
  >> 	module.exports = __webpack_require__.p + "a1ff28a4775f233223b49b3b098e1a79.ttf"
181:84: Missing semicolon. (code W033)
  >> 	module.exports = __webpack_require__.p + "d5b4083c3ec24c7a37460e236e4b0238.svg"
233:23: 'i' is already defined. (code W004)
  >> 			for(var i = 0; i < mayRemove.length; i++) {
234:30: 'domStyle' is already defined. (code W004)
  >> 				var domStyle = mayRemove[i];
242:6: Missing semicolon. (code W033)
  >> 	}
258:27: 'j' is already defined. (code W004)
  >> 				for(var j = 0; j < item.parts.length; j++) {
374:54: Missing semicolon. (code W033)
  >> 			styleElement.setAttribute("media", media)
522:24: Use '!==' to compare with 'null'. (code W041)
  >> 			return num != null ?
617:45: Use '!==' to compare with 'null'. (code W041)
  >> 			if ( (options = arguments[ i ]) != null ) {
673:24: Use '!==' to compare with 'null'. (code W041)
  >> 			return obj != null && obj === obj.window;
712:22: Use '===' to compare with 'null'. (code W041)
  >> 			if ( obj == null ) {
807:25: Use '===' to compare with 'null'. (code W041)
  >> 			return text == null ?
816:22: Use '!==' to compare with 'null'. (code W041)
  >> 			if ( arr != null ) {
831:24: Use '===' to compare with 'null'. (code W041)
  >> 			return arr == null ? -1 : indexOf.call( arr, elem, i );
880:32: Use '!==' to compare with 'null'. (code W041)
  >> 					if ( value != null ) {
890:32: Use '!==' to compare with 'null'. (code W041)
  >> 					if ( value != null ) {
1140:47: Expected an assignment or function call and instead saw an expression. (code W030)
  >> 		arr[ preferredDoc.childNodes.length ].nodeType;
2060:33: Use '===' to compare with 'null'. (code W041)
  >> 					if ( result == null ) {
2314:37: Expected an assignment or function call and instead saw an expression. (code W030)
  >> 					elem.parentNode.selectedIndex;
2359:58: Use '===' to compare with 'null'. (code W041)
  >> 					( (attr = elem.getAttribute("type")) == null || attr.toLowerCase() === "text" );
2582:26: Use '!==' to compare with 'null'. (code W041)
  >> 			mapped = map != null;
2762:63: Use '===' to compare with 'null'. (code W041)
  >> 					dirrunsUnique = (dirruns += contextBackup == null ? 1 : Math.random() || 0.1),
2773:56: Use '!==' to compare with 'null'. (code W041)
  >> 				for ( ; i !== len && (elem = elems[i]) != null; i++ ) {
3007:45: Use '===' to compare with 'null'. (code W041)
  >> 		return div.getAttribute("disabled") == null;
3363:39: Use '===' to compare with 'null'. (code W041)
  >> 			return this.add( selector == null ?
3684:36: Use '!==' to compare with 'null'. (code W041)
  >> 						return obj != null ? jQuery.extend( obj, promise ) : promise;
3882:24: Use '===' to compare with 'null'. (code W041)
  >> 			bulk = key == null;
4721:25: Use '===' to compare with 'null'. (code W041)
  >> 			data = data == null ?
4922:34: Use '===' to compare with 'null'. (code W041)
  >> 				if ( event.which == null ) {
4923:53: Use '!==' to compare with 'null'. (code W041)
  >> 					event.which = original.charCode != null ? original.charCode : original.keyCode;
4937:34: Use '===' to compare with 'null'. (code W041)
  >> 				if ( event.pageX == null && original.clientX != null ) {
4937:62: Use '!==' to compare with 'null'. (code W041)
  >> 				if ( event.pageX == null && original.clientX != null ) {
5239:23: Use '===' to compare with 'null'. (code W041)
  >> 			if ( data == null && fn == null ) {
5239:37: Use '===' to compare with 'null'. (code W041)
  >> 			if ( data == null && fn == null ) {
5243:28: Use '===' to compare with 'null'. (code W041)
  >> 			} else if ( fn == null ) {
5667:39: Use '!==' to compare with 'null'. (code W041)
  >> 			for ( ; (elem = elems[i]) != null; i++ ) {
5687:38: Use '!==' to compare with 'null'. (code W041)
  >> 			for ( ; (elem = this[i]) != null; i++ ) {
5702:43: Use '===' to compare with 'null'. (code W041)
  >> 			dataAndEvents = dataAndEvents == null ? false : dataAndEvents;
5703:51: Use '===' to compare with 'null'. (code W041)
  >> 			deepDataAndEvents = deepDataAndEvents == null ? dataAndEvents : deepDataAndEvents;
6082:47: Use '===' to compare with 'null'. (code W041)
  >> 					if ( boxSizingReliableVal == null ) {
6237:30: Use '===' to compare with 'null'. (code W041)
  >> 		if ( val <= 0 || val == null ) {
6240:33: Use '===' to compare with 'null'. (code W041)
  >> 			if ( val < 0 || val == null ) {
6390:28: Use '===' to compare with 'null'. (code W041)
  >> 				if ( value == null || value !== value ) {
6624:47: Use '!==' to compare with 'null'. (code W041)
  >> 				if ( tween.elem[ tween.prop ] != null &&
6625:74: Use '===' to compare with 'null'. (code W041)
  >> 					(!tween.elem.style || tween.elem.style[ tween.prop ] == null) ) {
6643:101: Use '!==' to compare with 'null'. (code W041)
  >> 				} else if ( tween.elem.style && ( tween.elem.style[ jQuery.cssProps[ tween.prop ] ] != null || jQuery.cssHooks[ tween.prop ] ) ) {
6791:33: Use '===' to compare with 'null'. (code W041)
  >> 			if ( hooks.unqueued == null ) {
6791:33: Too many errors. (51% scanned). (code E043)
  >> undefined
```

**Comment by lukeapage** [comment] 2015-07-08 21:12
Thanks. I see the problem. It seems to be stuck on the initial `lookupBlockType` call.

**Comment by lukeapage** [comment] 2015-07-08 22:04
I created a PR to fix this bug - #2538

**Comment by rondonjon** [comment] 2015-07-09 08:39
Thank you!

**Comment by SirZach** [comment] 2015-07-27 18:59
@rondonjon I am seeing the same issue and found the exact commit where things start to go awry https://github.com/jshint/jshint/commit/813d97a8f5d96f2ab8320ad5da63662195f79d6c. I'm glad to see that there's already a PR to fix the issue and can't wait for it to be merged in!

**Closed** 2015-08-27 17:42 UTC
Labels: Has PR, P1, Regression
