### ISSUE TITLE
Bogus warning "confusing use of '!'" thrown even though the '==' expression is wrapped in parenthesis

### ISSUE THREAD

**Issue by hasenj** [jshint/jshint#1486] opened 2014-01-23 17:09 UTC
This snippet:

    if(!(options.status == 'full')) {
    }

bogusly raises a warning `Confusing use of '!'.`, even though the expression is wrapped in parenthesis.

However, this snippet, (correctly) does not raise the warning:

    if(!('status' in options && options.status == 'full')) {
    }

How to reproduce:

Go to http://jshint.com/

Paste this code:

```
function main(options) {
    if(!(options.status == 'full')) {
    }
}

main();
```

You will notice the warning.

> 2	Confusing use of '!'.

Now, change it to this:

```
function main(options) {
    if(!('status' in options && options.status == 'full')) {
    }
}

main();
```

and the warning disappears.

**Comment by lukeapage** [comment] 2015-06-29 11:38
why do you think the param should make a difference? it is less confusing to write
```
function main(options) {
    if(options.status != 'full') {
    }
}
```

You can disable by disabling `W018` See #780 which this is a duplicate of

**Closed by lukeapage** 2015-06-29 11:38 UTC

**Comment by qm3ster** [comment] 2016-01-05 21:48
Please help me rewrite
```javascript
if /*jshint -W018 */ (data === undefined || !(data.length > 0)) /*jshint +W018 */ {}
```
in a non-confusing way?
