### ISSUE TITLE
double define variable in if {} else {} problem

### ISSUE THREAD

**Issue by MaxiBul** [jshint/jshint#2768] opened 2015-11-17 12:50 UTC
Problem code:
`if ($foo)`
`{`
`  // ...`
`  var name = "a1";`
`}`
`else`
`  var name = "a2";`

jshint swears on second definition: `'name' is already defined.`
Is it correct message?

**Comment by nicolo-ribaudo** [comment] 2015-11-17 14:07
I can't reproduce this issue:
![issue-2768](https://cloud.githubusercontent.com/assets/7000710/11213557/ea94d126-8d3c-11e5-8eb6-76b085bbe86a.jpeg)

**Comment by MaxiBul** [comment] 2015-11-17 14:37
Update:
`function funcName()`
`{`
`	if (foo)`
`       {`
`// ...`
`		var name = "a1";`
`       }`
`	else`
`		var name = "a2";`
`}`

**Comment by nicolo-ribaudo** [comment] 2015-11-17 14:59
You have to use `shadow: true`:
```js
// jshint shadow: true
function funcName() {
  if (foo) {
    // ...
    var name = "a1";
  } else {
    var name = "a2";
  }
}
```

Related/Duplicate - #2654

**Comment by jugglinmike** [comment] 2015-11-21 21:00
Thanks for the report! This is indeed a duplicate of gh-2654, so I'm going to close this one.

**Closed by jugglinmike** 2015-11-21 21:00 UTC
