### ISSUE TITLE
Permit destructuring patterns to have number, string and computed names

### ISSUE THREAD

**Issue by webbedspace** [jshint/jshint#2533] opened 2015-07-08 12:39 UTC
The following code will wrongly be considered erroneous:
```
const { 0:a, "1":b, [2]:c } = [5,6,7];
```
All three of these names are valid in destructuring patterns in ES6.

**Comment by lukeapage** [comment] 2015-07-08 12:45
duplicate of #2467
Will be fixed in next release (after 2.8.0)

**Closed by lukeapage** 2015-07-08 12:45 UTC
