### ISSUE TITLE
[ES6] Block-scope variable cannot be used before was defined

### ISSUE THREAD

**Issue by biqing** [jshint/jshint#2490] opened 2015-06-28 05:44 UTC
I was playing around with ES6, and found a case that jshint missed a hint.

```
{
    console.log(x);
    let x = 2;
}
```
normally, jshint can show the error " 'x' is not defined ".

```
{
    console.log(typeof x);
    let x = 2;
}
```
but when the variable is used as the param of 'typeof' operator, jshint can't find out the variable is not defined, which can lead to a runtime error.

**Comment by lukeapage** [comment] 2015-06-28 05:56
Duplicate of https://github.com/jshint/jshint/issues/2455

**Closed by lukeapage** 2015-06-28 05:56 UTC
