### ISSUE TITLE
Generate error on specific object properties

### ISSUE THREAD

**Issue by erosman** [jshint/jshint#3646] opened 2023-05-10 08:43 UTC
[JSHint Options](https://jshint.com/docs/options/) has [globals](https://jshint.com/docs/options/#globals) option.

>  This option can be used to specify a white list of global variables that are not formally defined in the source code.

I am face with a situation that I need to disallow certain `object` properties.

```js
globals: {
  GM: {},
  // ...
}
```

For example, I need to disallow (generate error) for `GM.one`, `GM. five`, ... etc.
ATM, I run a RegEx and manually generate the error to pass to CodeMirror. 

Is there a way to achieve that within JSHint?

**Comment by jugglinmike** [comment] 2023-06-16 01:26
Thanks for taking the time to file a report! This is a duplicate of [an existing feature request](https://github.com/jshint/jshint/issues/2914), where you'll find my perspective on the topic. In the interest of keeping things organized, let's continue the discussion there.

**Closed as not planned by jugglinmike** 2023-06-16 01:26 UTC
Labels: Duplicate
