### ISSUE TITLE
Infinite validation process (100% processor loading)

### ISSUE THREAD

**Issue by mctep** [jshint/jshint#2385] opened 2015-05-14 14:26 UTC
Hello!
Thank you for your great job.

Steps to reproduce the problem:

```sh
$ jshint -v
jshint v2.7.0
$ echo 'function' > test.js
$ jshint test.js
**nothing happens, only 100% processor loading**
```

Systems:
```
OS X Yosemite 10.10.3 (14D136)
```
and
```
Linux version 3.2.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.65-1+deb7u2
```

There are no problems with `jshint v2.6.3`

**Comment by jugglinmike** [comment] 2015-05-14 14:49
Thanks for the thorough report! Bad news: this is a duplicate of gh-2362 ("JSHINT('function') causes infinite loop in 2.7.0"). Good news: gh-2338 has landed, so this should be resolved in the next release of JSHint (version > 2.7.0).

**Closed by jugglinmike** 2015-05-14 14:49 UTC

**Comment by mctep** [comment] 2015-05-14 14:53
Great! :sunglasses:
