### ISSUE TITLE
Unused variables (W098) cannot be ignored if enabled at global level

### ISSUE THREAD

**Issue by chancancode** [jshint/jshint#1140] opened 2013-06-13 21:05 UTC
Linting the following piece of code:

```javascript
/*jshint forin:true, unused:true */

/*jshint -W089 *//*jshint -W098 */
var isEmpty = function(object){
  for (var _ in object) { return false; }
  return true;
};
/*jshint +W089 *//*jshint +W098 */

isEmpty({});
```

Causes jshint to report `W098: '_' is defined but never used.` but not `W089: The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.`

Removing the global `/*jshint forin:true, unused:true */` fixes it.

**Comment by nicolo-ribaudo** [comment] 2015-07-21 12:09
Can't reproduce on master

**Comment by lukeapage** [comment] 2015-07-21 12:20
I referenced this from my pr but it must have been a commit as it has disappeared. Its hard to see how this didn't used to work, but not unused are calculated as you leave the scope they apply to (so for `var` - the function scope) and they'll pick up any options.

**Comment by lukeapage** [comment] 2015-07-21 12:21
fixed in master, will be in next release.

**Closed by lukeapage** 2015-07-21 12:21 UTC
Labels: cannot reproduce or not an issue, P2
