### ISSUE TITLE
node / strict / not whining about global object declaration / not enforcing file level use strict

### ISSUE THREAD

**Issue by lukeavsec** [jshint/jshint#2550] opened 2015-07-13 14:23 UTC
The following is a nodejs module:

```javascript
foo = {
    bar: true
};
    
module.exports = foo;
```

both the strict and node options are set to true for jshint:

```javascript
{
    strict: true,
    node: true
}
```

jshint is not complaining at all that

if I insert a `'use strict';` declaration at the top of the file, it does complain about the variable being referenced in the global scope

how can I configure so that - even if there are no functions in a nodejs module that jshint still complains that I need to set `'use strict';` somewhere

I raise this as in issue only because I think the docs might be counterintuitive. And or there might not even be a way to do this.

Any help is greatly appreciated. I love JSHint and appreciate all the hard work.

**Comment by jugglinmike** [comment] 2015-07-13 14:29
See gh-2469. In the next minor release of JSHint (post-2.8.0), you'll be able to set the `strict` option to "implied". Please note, however, that without an explicit directive prologue, your code will not be interpreted in strict mode at runtime.

**Comment by lukeapage** [comment] 2015-07-17 06:23
duplicate of #924

**Closed by lukeapage** 2015-07-17 06:23 UTC
