### ISSUE TITLE
when using jshint ignore, Expected an identifier and instead saw ')' throws

### ISSUE THREAD

**Issue by hefangshi** [jshint/jshint#2710] opened 2015-10-08 09:16 UTC
When I use jshint@2.1.9, everything is fine, but after i update jshint to 2.3.0+, strange error throws.

Source Code

```
var tpl = function(a
      /**/){
};
```

Could pass jshint even in http://jshint.com/

![image](https://cloud.githubusercontent.com/assets/613846/10362303/61d2e2f4-6de0-11e5-87af-24eef55fb230.png)

But once with `jshint ignore:start`, it throw an error `Expected an identifier and instead saw ')'`

```
/* jshint ignore:start */
var tpl = function(a
      /**/){
};
/* jshint ignore:end */
```

![image](https://cloud.githubusercontent.com/assets/613846/10362288/401f1a1a-6de0-11e5-9105-4b84a3e513a2.png)

**Comment by nicolo-ribaudo** [comment] 2015-10-08 14:37
Duplicate of #2598

**Comment by hefangshi** [comment] 2015-10-08 17:14
@nicolo-ribaudo #2598 says `Lines inside an ignore section cannot start with a comment or they will not be ignored.` 

But my issue the comment is in the middle.

**Comment by nicolo-ribaudo** [comment] 2015-10-08 17:17
> But in my issue, the comment is in the middle.

It is the first token of the line

**Comment by hefangshi** [comment] 2015-10-08 17:29
got it, thanks ;)

Is there any workaround for this issue?

**Closed** 2015-10-10 15:36 UTC

**Comment by nicolo-ribaudo** [comment] 2015-10-11 13:19
> Is there any workaround for this issue?

If you are using JSHint through the nodejs api, you can do something like this:

```js
source = source.replace(/^(?:[ \t]*\/\*(?![\s]*(?:js[hl]int|globals?|exported) )(\s|.)*?\*\/)+/gm, function(match) {
  var nls = 0, spaces = 0;
  for (var i = 0; i < match.length; i++) {
    spaces++;
    if (match[i] === "\n") {
      nls++;
      spaces = 0;
    }
  }
  return new Array(nls + 1).join("\n") + new Array(spaces + 1).join(" ");
});
JSHINT(source, options);
```

That ugly regex removes every `/*` comment at the start of the line, expect for jshint configuration. If you don't care about position of the error, you can replace the whole function with `""`.

**Comment by hefangshi** [comment] 2015-10-11 14:39
@nicolo-ribaudo awesome! thanks ;)
