### ISSUE TITLE
"'name' is already defined" error when using 'let'

### ISSUE THREAD

**Issue by bcamper** [jshint/jshint#2138] opened 2015-01-29 23:03 UTC
When using `let name` to declare a variable, `'name' is already defined` warnings are generated. 

For example:
```
function test() {
  let x = ['a', 'b', 'c'];
  
  for (let name of x) {
    let y = name;
  }
   
  for (let name of x) {
  	let y = name;
  }
}

test();
```

Output: `8: 'name' is already defined.`

With a different variable name:
```
function test() {
  let x = ['a', 'b', 'c'];
  
  for (let xname of x) {
    let y = xname;
  }
   
  for (let xname of x) {
  	let y = xname;
  }
}

test();
```

No warnings are generated. (Run on http://jshint.com/ with esnext option on.)

As far as I'm aware there's no reason `name` should be reserved or should trigger a duplicate warning with block scope. Am I missing something?

**Comment by caitp** [comment] 2015-01-29 23:06
probably a bug =)

**Comment by caitp** [comment] 2015-01-29 23:34
I can't reproduce this in a unit test

Tried the following:

```js
exports["let statement in for loop with 'name' binding"] = function(test) {
  var code = [
    "let x = ['a', 'b', 'c'];",
    "for (let name of x) {",
    "  let y = name;",
    "  print(y);",
    "}",
    "for (let name of x) {",
    "  let y = name;",
    "  print(y);",
    "}",
    "}",
    "test();"
  ];

  TestRun(test)
    .test(code, {esnext: true, unused: true, undef: true, predef: ["print"]});
  test.done();
};
```

and

```js
exports["let statement in for loop with 'name' binding"] = function(test) {
  var code = [
    "function test() {",
    "let x = ['a', 'b', 'c'];",
    "for (let name of x) {",
    "  let y = name;",
    "  print(y);",
    "}",
    "for (let name of x) {",
    "  let y = name;",
    "  print(y);",
    "}",
  ];

  TestRun(test)
    .test(code, {esnext: true, unused: true, undef: true, predef: ["print"]});
  test.done();
};
```

**Comment by bcamper** [comment] 2015-01-29 23:57
OK, originally observed this in my code and then repro'ed the above example on jshint.com (default settings + esnext -- not sure exactly what settings that equals). I can try to repro in another isolated example.

**Comment by caitp** [comment] 2015-01-30 01:00
it's possible that this was a bug that was fixed recently, @jugglinmike / @rwaldron do you know anything about that?

**Comment by jugglinmike** [comment] 2015-01-30 01:16
This looks like a weird issue with shadowing a global from a `let` binding in a for...of statement. (`name` in this case throws an error on the JSHint website because the website sets `browser: true` by default.)

Here's another way to reproduce this for tests:

```js
/* jshint esnext: true, unused: false */
/* global name: true */
function test() {
  'use strict';
  for (let name of []) {
   let x = name;
  }

  for (let name of []) {}
}
```

It's still super complex, but I believe everything from the `for in` (i.e. not a simple `let` statement) to the `global` (i.e. not a `var` in the outer scope) are necessary. Weird!

**Comment by bcamper** [comment] 2015-01-30 02:22
Thanks @caitp and @jugglinmike for looking into it. Admittedly it's probably low priority, but I ran into it a few times and finally wanted to figure out what was going on.

**Comment by niligulmohar** [comment] 2015-02-26 21:46
I have a smaller test case for what might be the same bug:
```javascript
exports["make sure let variables may shadow predef globals in functions after they are referenced"] = function (test) {
  var code = [
    "function x() {",
    "  foo();",
    "  {",
    "    let foo;",
    "  }",
    "}"
  ];

  TestRun(test).test(code, { esnext: true, predef: ["foo"] });
  test.done();
};
```
This fails with:
```
Assertion Message: 
  [yellow]{Errors thrown by JSHINT, but not defined in test run}
  [bold]{Line 4, Char 12} 'foo' is already defined.
```
The test passes if you remove the predef, if you remove the reference to `foo`, or if you put the reference after the block.

**Comment by niligulmohar** [comment] 2015-02-27 00:09
Shorter test and suggested fix in #2199.

**Comment by niligulmohar** [comment] 2015-02-27 14:43
While #2199 fixes the erroneous redefinition warnings, there is still the issue that when parsing this code:
```javascript
/* jshint browser: true, unused: false */
function test() {
  let x = ['a', 'b', 'c'];

  for (let name of x) {
    let y = name; // <==
  }

  for (let name of x) {
  }
}
```
... the indicated reference to `name` puts it in the `funct` scope as a global. I'm not yet sure how to expose this with a test, but it seems like it could cause other problems.

**Comment by jugglinmike** [comment] 2015-04-15 23:32
This issue was resolved via gh-2214 and [released in JSHint version 2.7.0](https://github.com/jshint/jshint/releases/tag/2.7.0). Please re-open if you're still having trouble after upgrading!

**Closed by jugglinmike** 2015-04-15 23:32 UTC

**Comment by bcamper** [comment] 2015-04-16 02:53
Thanks!

**Comment by OmgImAlexis** [comment] 2016-02-01 11:41
I think I'm getting the same issue described here with [this](https://github.com/OmgImAlexis/cz/blob/master/index.js) inparticular [line 44](https://github.com/OmgImAlexis/cz/blob/master/index.js#L44).

I'm using a `for of` loop in two places with `let` and I get `index.js: line 44, col 30, 'prop' is already defined.` from jshint v2.8.0.
