### ISSUE TITLE
class property initializers proposal

### ISSUE THREAD

**Issue by torarnek** [jshint/jshint#2309] opened 2015-04-14 08:27 UTC
This [proposal] (https://gist.github.com/jeffmo/054df782c05639da2adb) is for ES7, which I think might get through, anyways, it is so useful that I wish to start using it in our projects. So support for this in JSHint would be great.

```javascript
class Person {
  firstName = "Sebastian";
  static lastName = "McKenzie";
}

assert(new Person().firstName, "Sebastian");
assert(Person.lastName, "McKenzie");
```

**Comment by topaxi** [comment] 2015-04-14 08:32
This is a duplicate of https://github.com/jshint/jshint/issues/2304

**Closed** 2015-04-14 08:34 UTC

**Comment by jugglinmike** [comment] 2017-06-03 17:03
Now that this proposal has reached stage 2, I have created an issue to track support within JSHint. See gh-3139.
