### ISSUE TITLE
using ES6 named parameters throws W116 and E030

### ISSUE THREAD

**Issue by meonkeys** [jshint/jshint#2651] opened 2015-08-28 21:03 UTC
Repro by linting this script with jshint v2.8.0:

```javascript
/* jshint esnext: true */
class Foo {
  f({blah=5, baz=10} = {}) {
  }
}
```

`jshint --verbose` output:

```
test.js: line 3, col 10, Expected ',' and instead saw '='. (W116)
test.js: line 3, col 11, Expected an identifier and instead saw '5'. (E030)
test.js: line 3, col 17, Expected ',' and instead saw '='. (W116)
test.js: line 3, col 18, Expected an identifier and instead saw '10'. (E030)

4 errors
```

**Comment by nicolo-ribaudo** [comment] 2015-08-29 16:43
Duplicate of #1941, the fix will land in the next release.

**Closed** 2015-09-06 07:11 UTC
