### ISSUE TITLE
Expected '(end)' and instead saw '}'. when trying to ignore javascript

### ISSUE THREAD

**Issue by nowherenearithaca** [jshint/jshint#2032] opened 2014-12-13 02:11 UTC
I'm using the autoNumeric plugin and wanted to have jshint ignore it.  I tried using `/*jshint ignore:start */` and then wrapping it with /*jshint ignore:end */ and it gets the weird error mentioned in the subject:

Expected '(end)' and instead saw '}'. when trying to ignore javascript

I verified that the error occurs in the little tester you have at http://jshint.com/ with the file https://raw.githubusercontent.com/BobKnothe/autoNumeric/master/autoNumeric.js

The only thing that jumps out at me initially is the comment /** blah */ on this line

**Comment by lukeapage** [comment] 2015-07-02 21:26
I am not able to reproduce any errors like that on jshint.com, but because your link is to master, it could be that the content changed. Are you able to offer a test case so I can see if this is still a problem?

I suspect it will be fixed in the next release by #2512 but I cannot verify without a test case.

**Closed** 2015-07-11 16:34 UTC
Labels: cannot reproduce or not an issue
