### ISSUE TITLE
ES6: Expected ',' and instead saw '='

### ISSUE THREAD

**Issue by monolithed** [jshint/jshint#2387] opened 2015-05-14 23:31 UTC
```js
let foo = {
  bar ({a, b, c = {}}) {
      return arguments;
  }
};

foo(0, 1);
```

**Expected ',' and instead saw '='**

**Comment by caitp** [comment] 2015-05-14 23:47
Yeah, last I looked at it the method parsing code  didn't deal with optional arguments, maybe not destructing either. Should be a good first big if anyone else is interested in sending a PR

**Comment by nicolo-ribaudo** [comment] 2015-05-15 19:20
Duplicate of #1941 :wink: 

(I'm working on this)

**Closed** 2015-05-15 19:25 UTC
Labels: Duplicate, ES6, good first bug, P2
