### ISSUE TITLE
What is the expected behaviour for non-existent files?

### ISSUE THREAD

**Issue by da99** [jshint/jshint#2884] opened 2016-03-03 23:23 UTC
I'm using `jshint` on `npm` and command line. When a file does not exist,  is `jshint` suppose to exit 0?

```sh
   jshint  file-does-not-exist
```

**Comment by jugglinmike** [comment] 2016-03-04 14:51
It looks like the behavior of the CLI is not documented for that case. Patching the CLI to return a non-zero exit code makes sense to me.

**Comment by jugglinmike** [comment] 2016-04-24 19:46
As it turns out, this is a duplicate of an existing issue: gh-1405. I'm going to close this in favor of that one.

**Closed by jugglinmike** 2016-04-24 19:46 UTC
Labels: Duplicate
