### ISSUE TITLE
JSHint errors in sublime not matching command-line

### ISSUE THREAD

**Issue by gk11** [jshint/jshint#3079] opened 2016-12-26 16:51 UTC
I recently started using ember-cli, and was following the tutorial on this page:
https://guides.emberjs.com/v2.10.0/tutorial/acceptance-test/. 
When linting the tutorial files in Sublime 3 (I'm using the "JSHint Gutter" package), I get this error on the first line of any JS file: "incompatible values for the 'undefined' and 'undefined' linting options".  The only way I could find to solve this is to comment the line: "esversion": 6 in .jshintrc, however that gives me errors when linting with "ember test --server": `acceptance/rentals-test.js: line 2, col 1, 'import' is only available in ES6 (use 'esversion: 6').`

I also get "...is not defined" errors on many ember methods/objects (in sublime & ember test), which I'm not getting in the command line (when running "ember server"). Aren't that suppose to look at the same .jshintrc file?  Adding the missing methods/object names in "predef" in .jshintrc solves the problem in sublime/ember-test, but then I have to keep adding new names as I go.

This is the script I'm working with:
```
import { test } from 'qunit';
import moduleForAcceptance from 'tutorial/tests/helpers/module-for-acceptance';

moduleForAcceptance('Acceptance | dashboard');

test('visiting /', function(assert) {
  visit('/');

  andThen(function() {
    assert.equal(currentURL(), '/');
  });
});
```

**Comment by jugglinmike** [comment] 2017-01-08 01:06
Are you able to reproduce this error by using JSHint directly? If so, could you also provide your `.jshintrc` file? My suspicion is that this is an error with the plugins and/or editor, but I may be wrong.

**Comment by jugglinmike** [comment] 2017-09-09 17:13
We can't move forward on this without more information. Since it's been a few months we've heard from you, I'm going to close this issue for now. We can re-open if you or anyone else can follow up.

**Closed by jugglinmike** 2017-09-09 17:13 UTC
Labels: Needs Information
